import type { EnLevel, EnWord, PartOfSpeech } from '@/english-engine/types';

/** Compact row: en | ar | pos | pronunciation | example | example (ar) | category */
type Row = string;

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

function parse(level: EnLevel, rows: Row[]): EnWord[] {
  return rows.map((r) => {
    const [en, ar, pos, pron, exEn, exAr, category] = r.split('|').map((x) => x.trim());
    return {
      id: `w-${slug(en!)}`,
      en: en!,
      ar: ar!,
      pos: pos as PartOfSpeech,
      pron: pron!,
      exEn: exEn!,
      exAr: exAr!,
      level,
      category: category!,
    };
  });
}

const STARTER: Row[] = [
  'hello|مرحبا|interj|heh-LOH|Hello, my name is Sam.|مرحبا، اسمي سام.|greetings',
  'goodbye|إلى اللقاء|interj|good-BYE|Goodbye, see you tomorrow.|إلى اللقاء، أراك غدا.|greetings',
  'please|من فضلك|adv|PLEEZ|Please sit down.|من فضلك اجلس.|greetings',
  'thank you|شكرا لك|phrase|THANK yoo|Thank you for your help.|شكرا لك على مساعدتك.|greetings',
  'sorry|آسف|adj|SOR-ee|I am sorry I am late.|أنا آسف لأنني متأخر.|greetings',
  'yes|نعم|interj|YES|Yes, I am a student.|نعم، أنا طالب.|basics',
  'no|لا|interj|NOH|No, I am not tired.|لا، لست متعبا.|basics',
  'name|اسم|noun|NAYM|My name is Lina.|اسمي لينا.|basics',
  'I|أنا|pron|EYE|I am from Egypt.|أنا من مصر.|pronouns',
  'you|أنت|pron|YOO|You are my friend.|أنت صديقي.|pronouns',
  'he|هو|pron|HEE|He is a doctor.|هو طبيب.|pronouns',
  'she|هي|pron|SHEE|She is a teacher.|هي معلمة.|pronouns',
  'we|نحن|pron|WEE|We are friends.|نحن أصدقاء.|pronouns',
  'they|هم|pron|THAY|They are at home.|هم في البيت.|pronouns',
  'it|هو / هي (لغير العاقل)|pron|IT|It is a book.|إنه كتاب.|pronouns',
  'am|أكون (مع I)|verb|AM|I am happy.|أنا سعيد.|be verb',
  'is|يكون (مفرد)|verb|IZ|She is tall.|هي طويلة.|be verb',
  'are|يكونون / تكون|verb|AR|They are students.|هم طلاب.|be verb',
  'one|واحد|num|WUN|I have one brother.|عندي أخ واحد.|numbers',
  'two|اثنان|num|TOO|I have two books.|عندي كتابان.|numbers',
  'three|ثلاثة|num|THREE|Three cats are here.|ثلاث قطط هنا.|numbers',
  'four|أربعة|num|FOR|We have four chairs.|عندنا أربعة كراسي.|numbers',
  'five|خمسة|num|FIVE|I am five years old.|عمري خمس سنوات.|numbers',
  'six|ستة|num|SIKS|Six students are absent.|ستة طلاب غائبون.|numbers',
  'seven|سبعة|num|SEV-un|A week has seven days.|الأسبوع سبعة أيام.|numbers',
  'eight|ثمانية|num|AYT|It is eight o’clock.|الساعة الثامنة.|numbers',
  'nine|تسعة|num|NINE|I have nine pens.|عندي تسعة أقلام.|numbers',
  'ten|عشرة|num|TEN|Ten people are here.|عشرة أشخاص هنا.|numbers',
  'red|أحمر|adj|RED|The apple is red.|التفاحة حمراء.|colors',
  'blue|أزرق|adj|BLOO|The sky is blue.|السماء زرقاء.|colors',
  'green|أخضر|adj|GREEN|The tree is green.|الشجرة خضراء.|colors',
  'yellow|أصفر|adj|YEL-oh|The sun is yellow.|الشمس صفراء.|colors',
  'black|أسود|adj|BLAK|My cat is black.|قطتي سوداء.|colors',
  'white|أبيض|adj|WYT|The wall is white.|الجدار أبيض.|colors',
  'mother|أم|noun|MUH-ther|My mother is kind.|أمي لطيفة.|family',
  'father|أب|noun|FAH-ther|My father is at work.|أبي في العمل.|family',
  'brother|أخ|noun|BRUH-ther|He is my brother.|هو أخي.|family',
  'sister|أخت|noun|SIS-ter|She is my sister.|هي أختي.|family',
  'friend|صديق|noun|FREND|He is my friend.|هو صديقي.|family',
  'family|عائلة|noun|FAM-uh-lee|I love my family.|أحب عائلتي.|family',
  'boy|ولد|noun|BOY|The boy is happy.|الولد سعيد.|people',
  'girl|بنت|noun|GURL|The girl is nice.|البنت لطيفة.|people',
  'man|رجل|noun|MAN|The man is tall.|الرجل طويل.|people',
  'woman|امرأة|noun|WUUM-un|The woman is a doctor.|المرأة طبيبة.|people',
  'teacher|معلم|noun|TEE-cher|My teacher is kind.|معلمي لطيف.|people',
  'student|طالب|noun|STOO-dent|I am a student.|أنا طالب.|people',
  'doctor|طبيب|noun|DOK-ter|The doctor is here.|الطبيب هنا.|people',
  'house|بيت|noun|HOWS|My house is big.|بيتي كبير.|places',
  'school|مدرسة|noun|SKOOL|I go to school.|أذهب إلى المدرسة.|places',
  'room|غرفة|noun|ROOM|This is my room.|هذه غرفتي.|places',
  'book|كتاب|noun|BUUK|This is a book.|هذا كتاب.|things',
  'pen|قلم|noun|PEN|I have a pen.|عندي قلم.|things',
  'bag|حقيبة|noun|BAG|My bag is heavy.|حقيبتي ثقيلة.|things',
  'table|طاولة|noun|TAY-bul|The book is on the table.|الكتاب على الطاولة.|things',
  'chair|كرسي|noun|CHAIR|Sit on the chair.|اجلس على الكرسي.|things',
  'door|باب|noun|DOR|Open the door.|افتح الباب.|things',
  'water|ماء|noun|WAW-ter|I drink water.|أشرب الماء.|food',
  'bread|خبز|noun|BRED|I eat bread.|آكل الخبز.|food',
  'milk|حليب|noun|MILK|I like milk.|أحب الحليب.|food',
  'apple|تفاحة|noun|AP-ul|The apple is red.|التفاحة حمراء.|food',
  'egg|بيضة|noun|EG|I eat an egg.|آكل بيضة.|food',
  'tea|شاي|noun|TEE|I drink tea.|أشرب الشاي.|food',
  'big|كبير|adj|BIG|The house is big.|البيت كبير.|adjectives',
  'small|صغير|adj|SMAWL|The cat is small.|القطة صغيرة.|adjectives',
  'good|جيد|adj|GUUD|This is a good book.|هذا كتاب جيد.|adjectives',
  'bad|سيئ|adj|BAD|The weather is bad.|الطقس سيئ.|adjectives',
  'happy|سعيد|adj|HAP-ee|I am happy.|أنا سعيد.|adjectives',
  'sad|حزين|adj|SAD|He is sad today.|هو حزين اليوم.|adjectives',
  'hot|حار|adj|HOT|The tea is hot.|الشاي حار.|adjectives',
  'cold|بارد|adj|KOHLD|The water is cold.|الماء بارد.|adjectives',
  'new|جديد|adj|NYOO|I have a new bag.|عندي حقيبة جديدة.|adjectives',
  'old|قديم / كبير في السن|adj|OHLD|This is an old book.|هذا كتاب قديم.|adjectives',
  'cat|قطة|noun|KAT|The cat is small.|القطة صغيرة.|animals',
  'dog|كلب|noun|DOG|The dog is big.|الكلب كبير.|animals',
  'bird|طائر|noun|BURD|The bird is blue.|الطائر أزرق.|animals',
  'fish|سمكة|noun|FISH|I see a fish.|أرى سمكة.|animals',
  'have|يملك / عند|verb|HAV|I have a pen.|عندي قلم.|verbs',
  'like|يحب|verb|LYK|I like tea.|أحب الشاي.|verbs',
  'eat|يأكل|verb|EET|I eat bread.|آكل الخبز.|verbs',
  'drink|يشرب|verb|DRINK|I drink water.|أشرب الماء.|verbs',
  'go|يذهب|verb|GOH|I go to school.|أذهب إلى المدرسة.|verbs',
  'read|يقرأ|verb|REED|I read a book.|أقرأ كتابا.|verbs',
  'write|يكتب|verb|RYT|I write a letter.|أكتب رسالة.|verbs',
  'see|يرى|verb|SEE|I see a bird.|أرى طائرا.|verbs',
  'this|هذا / هذه|det|THIS|This is my book.|هذا كتابي.|basics',
  'that|ذلك / تلك|det|THAT|That is my house.|ذلك بيتي.|basics',
  'a|أداة نكرة (واحد)|det|uh|I have a pen.|عندي قلم.|basics',
  'the|أداة تعريف (ال)|det|thuh|The pen is red.|القلم أحمر.|basics',
  'my|ـي (ملكي)|det|MY|My name is Sam.|اسمي سام.|pronouns',
  'your|ـك (ملكك)|det|YOR|Your bag is blue.|حقيبتك زرقاء.|pronouns',
  'where|أين|adv|WAIR|Where is my pen?|أين قلمي؟|questions',
  'what|ماذا / ما|pron|WOT|What is your name?|ما اسمك؟|questions',
  'who|من|pron|HOO|Who is he?|من هو؟|questions',
  'how|كيف|adv|HOW|How are you?|كيف حالك؟|questions',
  'morning|صباح|noun|MOR-ning|Good morning!|صباح الخير!|time',
  'night|ليل|noun|NYT|Good night!|تصبح على خير!|time',
  'today|اليوم|adv|tuh-DAY|Today is Monday.|اليوم الاثنين.|time',
];

const A1: Row[] = [
  'breakfast|فطور|noun|BREK-fust|I eat breakfast at seven.|آكل الفطور في السابعة.|food',
  'lunch|غداء|noun|LUNCH|We have lunch at one.|نتناول الغداء في الواحدة.|food',
  'dinner|عشاء|noun|DIN-er|Dinner is ready.|العشاء جاهز.|food',
  'rice|أرز|noun|RYS|We eat rice and chicken.|نأكل الأرز والدجاج.|food',
  'chicken|دجاج|noun|CHIK-in|The chicken is delicious.|الدجاج لذيذ.|food',
  'vegetable|خضار|noun|VEJ-tuh-bul|Eat more vegetables.|تناول خضارا أكثر.|food',
  'fruit|فاكهة|noun|FROOT|I like fruit.|أحب الفاكهة.|food',
  'coffee|قهوة|noun|KAW-fee|He drinks coffee.|هو يشرب القهوة.|food',
  'juice|عصير|noun|JOOS|Orange juice, please.|عصير برتقال من فضلك.|food',
  'hungry|جائع|adj|HUNG-gree|I am hungry.|أنا جائع.|food',
  'thirsty|عطشان|adj|THUR-stee|She is thirsty.|هي عطشانة.|food',
  'wake up|يستيقظ|verb|WAYK UP|I wake up at six.|أستيقظ في السادسة.|routine',
  'get up|ينهض|verb|GET UP|He gets up early.|هو ينهض مبكرا.|routine',
  'wash|يغسل|verb|WOSH|I wash my hands.|أغسل يدي.|routine',
  'work|يعمل / عمل|verb|WURK|My father works in a bank.|أبي يعمل في بنك.|routine',
  'study|يدرس|verb|STUD-ee|I study English every day.|أدرس الإنجليزية كل يوم.|routine',
  'sleep|ينام|verb|SLEEP|I sleep at ten.|أنام في العاشرة.|routine',
  'cook|يطبخ|verb|KUUK|My mother cooks well.|أمي تطبخ جيدا.|routine',
  'play|يلعب|verb|PLAY|The children play outside.|الأطفال يلعبون في الخارج.|routine',
  'watch|يشاهد|verb|WOCH|We watch TV at night.|نشاهد التلفاز ليلا.|routine',
  'listen|يستمع|verb|LIS-un|Listen to the teacher.|استمع إلى المعلم.|routine',
  'speak|يتحدث|verb|SPEEK|Do you speak English?|هل تتحدث الإنجليزية؟|routine',
  'walk|يمشي|verb|WAWK|I walk to school.|أمشي إلى المدرسة.|routine',
  'run|يركض|verb|RUN|He runs every morning.|هو يركض كل صباح.|routine',
  'live|يعيش / يسكن|verb|LIV|I live in Cairo.|أسكن في القاهرة.|routine',
  'want|يريد|verb|WONT|I want some water.|أريد بعض الماء.|verbs',
  'need|يحتاج|verb|NEED|I need a pen.|أحتاج قلما.|verbs',
  'buy|يشتري|verb|BY|I buy bread every day.|أشتري الخبز كل يوم.|verbs',
  'open|يفتح|verb|OH-pun|Open the window.|افتح النافذة.|verbs',
  'close|يغلق|verb|KLOHZ|Close the door.|أغلق الباب.|verbs',
  'help|يساعد|verb|HELP|Can you help me?|هل تستطيع مساعدتي؟|verbs',
  'know|يعرف|verb|NOH|I know her name.|أعرف اسمها.|verbs',
  'think|يفكر / يظن|verb|THINK|I think it is good.|أظن أنه جيد.|verbs',
  'love|يحب بشدة|verb|LUV|I love my family.|أحب عائلتي كثيرا.|verbs',
  'give|يعطي|verb|GIV|Give me the book.|أعطني الكتاب.|verbs',
  'take|يأخذ|verb|TAYK|Take your bag.|خذ حقيبتك.|verbs',
  'come|يأتي|verb|KUM|Come here, please.|تعال إلى هنا من فضلك.|verbs',
  'make|يصنع|verb|MAYK|I make tea every morning.|أصنع الشاي كل صباح.|verbs',
  'Monday|الاثنين|noun|MUN-day|I have class on Monday.|عندي حصة يوم الاثنين.|days',
  'Tuesday|الثلاثاء|noun|TOOZ-day|Tuesday is a busy day.|الثلاثاء يوم مزدحم.|days',
  'Wednesday|الأربعاء|noun|WENZ-day|We meet on Wednesday.|نلتقي يوم الأربعاء.|days',
  'Thursday|الخميس|noun|THURZ-day|I work on Thursday.|أعمل يوم الخميس.|days',
  'Friday|الجمعة|noun|FRY-day|Friday is a holiday.|الجمعة عطلة.|days',
  'Saturday|السبت|noun|SAT-er-day|I rest on Saturday.|أرتاح يوم السبت.|days',
  'Sunday|الأحد|noun|SUN-day|Sunday is the first day.|الأحد هو اليوم الأول.|days',
  'week|أسبوع|noun|WEEK|There are seven days in a week.|في الأسبوع سبعة أيام.|time',
  'year|سنة|noun|YEER|This year is good.|هذه السنة جيدة.|time',
  'time|وقت|noun|TYM|What time is it?|كم الساعة؟|time',
  'always|دائما|adv|AWL-wayz|I always drink tea.|أشرب الشاي دائما.|time',
  'usually|عادة|adv|YOO-zhoo-ul-ee|I usually walk to work.|عادة أمشي إلى العمل.|time',
  'sometimes|أحيانا|adv|SUM-tymz|Sometimes we eat out.|أحيانا نأكل في الخارج.|time',
  'never|أبدا|adv|NEV-er|He never drinks coffee.|هو لا يشرب القهوة أبدا.|time',
  'tomorrow|غدا|adv|tuh-MOR-oh|See you tomorrow.|أراك غدا.|time',
  'yesterday|أمس|adv|YES-ter-day|I was at home yesterday.|كنت في البيت أمس.|time',
  'city|مدينة|noun|SIT-ee|Cairo is a big city.|القاهرة مدينة كبيرة.|places',
  'street|شارع|noun|STREET|The street is quiet.|الشارع هادئ.|places',
  'shop|متجر|noun|SHOP|The shop is open.|المتجر مفتوح.|places',
  'market|سوق|noun|MAR-kit|We go to the market on Friday.|نذهب إلى السوق يوم الجمعة.|places',
  'hospital|مستشفى|noun|HOS-pit-ul|The hospital is near.|المستشفى قريب.|places',
  'bank|بنك|noun|BANK|The bank is closed.|البنك مغلق.|places',
  'park|حديقة|noun|PARK|We play in the park.|نلعب في الحديقة.|places',
  'kitchen|مطبخ|noun|KICH-in|My mother is in the kitchen.|أمي في المطبخ.|home',
  'bedroom|غرفة نوم|noun|BED-room|My bedroom is small.|غرفة نومي صغيرة.|home',
  'bathroom|حمام|noun|BATH-room|The bathroom is upstairs.|الحمام في الطابق العلوي.|home',
  'window|نافذة|noun|WIN-doh|Open the window, please.|افتح النافذة من فضلك.|home',
  'bed|سرير|noun|BED|The bed is soft.|السرير ناعم.|home',
  'phone|هاتف|noun|FOHN|My phone is new.|هاتفي جديد.|things',
  'computer|حاسوب|noun|kum-PYOO-ter|I work on a computer.|أعمل على حاسوب.|things',
  'car|سيارة|noun|KAR|His car is red.|سيارته حمراء.|things',
  'bus|حافلة|noun|BUS|I take the bus to work.|أركب الحافلة إلى العمل.|things',
  'money|مال|noun|MUN-ee|I need some money.|أحتاج بعض المال.|things',
  'head|رأس|noun|HED|My head hurts.|رأسي يؤلمني.|body',
  'hand|يد|noun|HAND|Wash your hands.|اغسل يديك.|body',
  'eye|عين|noun|EYE|She has blue eyes.|عيناها زرقاوان.|body',
  'ear|أذن|noun|EER|I have two ears.|عندي أذنان.|body',
  'mouth|فم|noun|MOWTH|Open your mouth.|افتح فمك.|body',
  'foot|قدم|noun|FUUT|My foot hurts.|قدمي تؤلمني.|body',
  'tall|طويل|adj|TAWL|My brother is tall.|أخي طويل.|adjectives',
  'short|قصير|adj|SHORT|The table is short.|الطاولة قصيرة.|adjectives',
  'young|شاب / صغير في السن|adj|YUNG|She is young.|هي شابة.|adjectives',
  'beautiful|جميل|adj|BYOO-tih-ful|The garden is beautiful.|الحديقة جميلة.|adjectives',
  'busy|مشغول|adj|BIZ-ee|I am busy today.|أنا مشغول اليوم.|adjectives',
  'tired|متعب|adj|TY-erd|I am tired.|أنا متعب.|adjectives',
  'easy|سهل|adj|EE-zee|English is easy for me.|الإنجليزية سهلة علي.|adjectives',
  'difficult|صعب|adj|DIF-ih-kult|Math is difficult for him.|الرياضيات صعبة عليه.|adjectives',
  'fast|سريع|adj|FAST|The car is fast.|السيارة سريعة.|adjectives',
  'slow|بطيء|adj|SLOH|The bus is slow.|الحافلة بطيئة.|adjectives',
  'near|قريب|adj|NEER|The school is near.|المدرسة قريبة.|adjectives',
  'far|بعيد|adj|FAR|My work is far.|عملي بعيد.|adjectives',
  'in|في|prep|IN|The book is in the bag.|الكتاب في الحقيبة.|prepositions',
  'on|على|prep|ON|The pen is on the table.|القلم على الطاولة.|prepositions',
  'under|تحت|prep|UN-der|The cat is under the chair.|القطة تحت الكرسي.|prepositions',
  'next to|بجانب|prep|NEKST too|The bank is next to the shop.|البنك بجانب المتجر.|prepositions',
  'at|عند / في (وقت أو مكان)|prep|AT|I am at home.|أنا في البيت.|prepositions',
  'with|مع|prep|WITH|I go with my friend.|أذهب مع صديقي.|prepositions',
  'and|و|conj|AND|Tea and bread.|شاي وخبز.|basics',
  'but|لكن|conj|BUT|I am tired but happy.|أنا متعب لكن سعيد.|basics',
  'because|لأن|conj|bih-KUZ|I stay home because I am sick.|أبقى في البيت لأنني مريض.|basics',
];

const A2: Row[] = [
  'travel|يسافر|verb|TRAV-ul|I like to travel.|أحب السفر.|travel',
  'ticket|تذكرة|noun|TIK-it|I bought a train ticket.|اشتريت تذكرة قطار.|travel',
  'airport|مطار|noun|AIR-port|The airport is far.|المطار بعيد.|travel',
  'passport|جواز سفر|noun|PAS-port|Show your passport.|أرِ جواز سفرك.|travel',
  'hotel|فندق|noun|hoh-TEL|We stayed in a small hotel.|أقمنا في فندق صغير.|travel',
  'luggage|أمتعة|noun|LUG-ij|My luggage is heavy.|أمتعتي ثقيلة.|travel',
  'weather|طقس|noun|WETH-er|The weather is nice today.|الطقس جميل اليوم.|weather',
  'rain|مطر / تمطر|noun|RAYN|I like the rain.|أحب المطر.|weather',
  'sunny|مشمس|adj|SUN-ee|It is sunny today.|الجو مشمس اليوم.|weather',
  'cloudy|غائم|adj|KLOW-dee|It is cloudy this morning.|الجو غائم هذا الصباح.|weather',
  'decide|يقرر|verb|dih-SYD|I decided to learn English.|قررت تعلم الإنجليزية.|verbs',
  'remember|يتذكر|verb|rih-MEM-ber|I remember her name.|أتذكر اسمها.|verbs',
  'forget|ينسى|verb|fer-GET|Don’t forget your keys.|لا تنس مفاتيحك.|verbs',
  'learn|يتعلم|verb|LURN|I learn ten words a day.|أتعلم عشر كلمات يوميا.|verbs',
  'teach|يعلّم|verb|TEECH|She teaches math.|هي تدرّس الرياضيات.|verbs',
  'visit|يزور|verb|VIZ-it|We visit my uncle on Friday.|نزور عمي يوم الجمعة.|verbs',
  'invite|يدعو|verb|in-VYT|I invited my friends.|دعوت أصدقائي.|verbs',
  'carry|يحمل|verb|KAR-ee|Can you carry this bag?|هل تستطيع حمل هذه الحقيبة؟|verbs',
  'enjoy|يستمتع|verb|in-JOY|I enjoy reading.|أستمتع بالقراءة.|verbs',
  'prefer|يفضّل|verb|prih-FUR|I prefer tea to coffee.|أفضّل الشاي على القهوة.|verbs',
  'important|مهم|adj|im-POR-tunt|Sleep is important.|النوم مهم.|adjectives',
  'dangerous|خطير|adj|DAYN-jer-us|The road is dangerous.|الطريق خطير.|adjectives',
  'expensive|غالٍ|adj|ik-SPEN-siv|This phone is expensive.|هذا الهاتف غالٍ.|adjectives',
  'cheap|رخيص|adj|CHEEP|The bread is cheap.|الخبز رخيص.|adjectives',
  'comfortable|مريح|adj|KUMF-ter-bul|The bed is comfortable.|السرير مريح.|adjectives',
  'delicious|لذيذ|adj|dih-LISH-us|The soup is delicious.|الحساء لذيذ.|food',
  'recipe|وصفة طبخ|noun|RES-ih-pee|I have a good recipe.|عندي وصفة جيدة.|food',
  'ingredient|مكوّن|noun|in-GREE-dee-ent|Salt is an ingredient.|الملح مكوّن.|food',
  'neighbor|جار|noun|NAY-ber|My neighbor is friendly.|جاري ودود.|people',
  'customer|زبون|noun|KUS-tuh-mer|The customer is waiting.|الزبون ينتظر.|people',
  'manager|مدير|noun|MAN-ij-er|The manager is busy.|المدير مشغول.|people',
  'appointment|موعد|noun|uh-POINT-ment|I have an appointment at four.|عندي موعد في الرابعة.|work',
  'meeting|اجتماع|noun|MEE-ting|The meeting starts at nine.|يبدأ الاجتماع في التاسعة.|work',
  'message|رسالة|noun|MES-ij|I sent you a message.|أرسلت لك رسالة.|work',
  'problem|مشكلة|noun|PROB-lum|I have a problem.|عندي مشكلة.|work',
  'idea|فكرة|noun|eye-DEE-uh|That is a good idea.|هذه فكرة جيدة.|work',
  'quickly|بسرعة|adv|KWIK-lee|He walks quickly.|هو يمشي بسرعة.|adverbs',
  'carefully|بحذر|adv|KAIR-ful-ee|Drive carefully.|قد بحذر.|adverbs',
  'together|معا|adv|tuh-GETH-er|We study together.|ندرس معا.|adverbs',
  'maybe|ربما|adv|MAY-bee|Maybe he is at home.|ربما هو في البيت.|adverbs',
];

const B1: Row[] = [
  'achieve|يحقق|verb|uh-CHEEV|She achieved her goal.|حققت هدفها.|verbs',
  'improve|يحسّن|verb|im-PROOV|I want to improve my English.|أريد تحسين إنجليزيتي.|verbs',
  'suggest|يقترح|verb|sug-JEST|I suggest we leave early.|أقترح أن نغادر مبكرا.|verbs',
  'avoid|يتجنب|verb|uh-VOID|Avoid sugar if you can.|تجنب السكر إن استطعت.|verbs',
  'compare|يقارن|verb|kum-PAIR|Compare the two prices.|قارن بين السعرين.|verbs',
  'describe|يصف|verb|dih-SKRYB|Describe your house.|صف بيتك.|verbs',
  'manage|يتدبر / يدير|verb|MAN-ij|I managed to finish on time.|تمكنت من الانتهاء في الوقت.|verbs',
  'experience|خبرة / تجربة|noun|ik-SPEER-ee-ents|He has ten years of experience.|عنده عشر سنوات من الخبرة.|work',
  'opportunity|فرصة|noun|op-er-TOO-nih-tee|This is a great opportunity.|هذه فرصة عظيمة.|work',
  'responsible|مسؤول|adj|rih-SPON-sih-bul|She is responsible for the team.|هي مسؤولة عن الفريق.|work',
  'environment|بيئة|noun|in-VY-run-ment|We must protect the environment.|يجب أن نحمي البيئة.|society',
  'government|حكومة|noun|GUV-ern-ment|The government made a new law.|سنّت الحكومة قانونا جديدا.|society',
  'society|مجتمع|noun|suh-SY-uh-tee|Education helps society.|التعليم يخدم المجتمع.|society',
  'although|مع أن|conj|awl-THOH|Although it was late, we kept working.|مع أن الوقت تأخر، واصلنا العمل.|connectors',
  'however|لكن / غير أن|adv|how-EV-er|It is cheap. However, it is not good.|إنه رخيص. لكنه ليس جيدا.|connectors',
  'therefore|لذلك|adv|THAIR-for|He was sick; therefore, he stayed home.|كان مريضا؛ لذلك بقي في البيت.|connectors',
  'probably|غالبا|adv|PROB-uh-blee|It will probably rain.|غالبا ستمطر.|adverbs',
  'actually|في الحقيقة|adv|AK-choo-uh-lee|Actually, I disagree.|في الحقيقة أنا لا أوافق.|adverbs',
  'successful|ناجح|adj|suk-SES-ful|He is a successful engineer.|هو مهندس ناجح.|adjectives',
  'confident|واثق|adj|KON-fih-dent|She feels confident.|هي تشعر بالثقة.|adjectives',
  'available|متاح|adj|uh-VAY-luh-bul|Is this seat available?|هل هذا المقعد متاح؟|adjectives',
  'necessary|ضروري|adj|NES-ih-ser-ee|Water is necessary for life.|الماء ضروري للحياة.|adjectives',
  'accept|يقبل|verb|ak-SEPT|Please accept my apology.|من فضلك اقبل اعتذاري.|verbs',
  'refuse|يرفض|verb|rih-FYOOZ|He refused the offer.|رفض العرض.|verbs',
  'prepare|يحضّر|verb|prih-PAIR|I prepare dinner at six.|أحضّر العشاء في السادسة.|verbs',
  'organize|ينظّم|verb|OR-guh-nyz|We organized a small party.|نظّمنا حفلة صغيرة.|verbs',
  'consider|يفكر في / يعتبر|verb|kun-SID-er|Consider all the options.|فكّر في كل الخيارات.|verbs',
  'depend|يعتمد|verb|dih-PEND|It depends on the weather.|يعتمد على الطقس.|verbs',
  'article|مقال|noun|AR-tih-kul|I read an article about health.|قرأت مقالا عن الصحة.|media',
  'advice|نصيحة|noun|ad-VYS|Thank you for your advice.|شكرا على نصيحتك.|basics',
];

const B2: Row[] = [
  'significant|مهم / ملحوظ|adj|sig-NIF-ih-kunt|There was a significant change.|حدث تغيير ملحوظ.|academic',
  'consequence|نتيجة / عاقبة|noun|KON-sih-kwens|Every action has a consequence.|لكل فعل نتيجة.|academic',
  'assume|يفترض|verb|uh-SOOM|I assume you are ready.|أفترض أنك جاهز.|academic',
  'establish|يؤسس|verb|ih-STAB-lish|They established a new company.|أسسوا شركة جديدة.|academic',
  'perspective|وجهة نظر|noun|per-SPEK-tiv|Try to see it from my perspective.|حاول أن تراها من وجهة نظري.|academic',
  'inevitable|حتمي|adj|in-EV-ih-tuh-bul|Change is inevitable.|التغيير حتمي.|academic',
  'reluctant|متردد|adj|rih-LUK-tunt|He was reluctant to agree.|كان متردد في الموافقة.|academic',
  'deliberately|عمدا|adv|dih-LIB-er-it-lee|She deliberately ignored it.|تجاهلته عمدا.|academic',
  'overcome|يتغلب على|verb|oh-ver-KUM|He overcame his fear.|تغلب على خوفه.|verbs',
  'acknowledge|يعترف بـ|verb|ak-NOL-ij|I acknowledge my mistake.|أعترف بخطئي.|verbs',
  'emphasize|يؤكد على|verb|EM-fuh-syz|The teacher emphasized practice.|أكد المعلم على التدريب.|verbs',
  'contribute|يساهم|verb|kun-TRIB-yoot|Everyone should contribute.|يجب أن يساهم الجميع.|verbs',
  'sustainable|مستدام|adj|suh-STAY-nuh-bul|We need sustainable energy.|نحتاج طاقة مستدامة.|society',
  'inequality|عدم المساواة|noun|in-ih-KWOL-ih-tee|Inequality is a global problem.|عدم المساواة مشكلة عالمية.|society',
  'regulation|تنظيم / لائحة|noun|reg-yuh-LAY-shun|New regulations start in May.|تبدأ لوائح جديدة في مايو.|society',
  'nevertheless|ومع ذلك|adv|nev-er-thuh-LES|It was hard; nevertheless, we won.|كان صعبا؛ ومع ذلك فزنا.|connectors',
  'furthermore|علاوة على ذلك|adv|FUR-ther-mor|Furthermore, it saves money.|علاوة على ذلك، إنه يوفر المال.|connectors',
  'whereas|بينما|conj|wair-AZ|He is quiet, whereas she is loud.|هو هادئ بينما هي صاخبة.|connectors',
  'approximately|تقريبا|adv|uh-PROK-sih-mit-lee|It costs approximately ten dollars.|تكلف تقريبا عشرة دولارات.|academic',
  'considerable|كبير / جدير بالاعتبار|adj|kun-SID-er-uh-bul|It took considerable effort.|تطلب جهدا كبيرا.|academic',
  'attitude|موقف / اتجاه|noun|AT-ih-tood|A good attitude helps you learn.|الموقف الجيد يساعدك على التعلم.|academic',
  'evidence|دليل|noun|EV-ih-dens|There is no evidence.|لا يوجد دليل.|academic',
  'currently|حاليا|adv|KUR-unt-lee|I am currently studying.|أدرس حاليا.|academic',
  'recover|يتعافى|verb|rih-KUV-er|He recovered quickly.|تعافى بسرعة.|verbs',
  'struggle|يكافح|verb|STRUG-ul|Many people struggle with grammar.|كثيرون يعانون مع القواعد.|verbs',
];

export const WORDS: EnWord[] = [
  ...parse('starter', STARTER),
  ...parse('a1', A1),
  ...parse('a2', A2),
  ...parse('b1', B1),
  ...parse('b2', B2),
];

export const WORD_BY_ID: Record<string, EnWord> = Object.fromEntries(WORDS.map((w) => [w.id, w]));
export const wordId = (en: string): string => `w-${slug(en)}`;
export const wordsOfLevel = (level: EnLevel): EnWord[] => WORDS.filter((w) => w.level === level);
export const wordsOfCategory = (cat: string): EnWord[] => WORDS.filter((w) => w.category === cat);

/** Lowercase surface form → word, for tap-to-translate in readings. Includes simple plurals / -s / -ed forms. */
export const WORD_BY_FORM: Record<string, EnWord> = (() => {
  const m: Record<string, EnWord> = {};
  for (const w of WORDS) {
    const base = w.en.toLowerCase();
    m[base] = w;
    if (!base.includes(' ')) {
      for (const f of [base + 's', base + 'es', base + 'ed', base + 'd', base + 'ing']) m[f] ??= w;
    }
  }
  return m;
})();
