import {
  T, W, levelLessons, explain, examples, pronounce, vocabStep, tryIt, practice, summary,
  mcq, enAr, arEn, chooseWord, chooseSentence, complete, fill, fix, tf, recall, wordOrder, sentenceOrder, matching, listenChoose, listenType, written,
} from '../build';

export const A1_LESSONS = levelLessons('a1', [
  {
    id: 'a1-routine',
    title: T('My daily routine', 'روتيني اليومي'),
    summary: T('Talk about what you do every day.', 'تحدث عما تفعله كل يوم.'),
    minutes: 9,
    skills: ['vocab', 'grammar'],
    vocab: W('wake up', 'get up', 'wash', 'work', 'study', 'sleep'),
    grammarId: 'g-present-simple',
    steps: [
      explain(T('The present simple', 'المضارع البسيط'),
        T('Use the base verb for habits and routines: I wake up at six. I study English. No extra word is needed with I, you, we, they.', 'استخدم الفعل كما هو للعادات والروتين: I wake up at six. I study English. ولا حاجة لكلمة إضافية مع I و you و we و they.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I wake up at six.', ar: 'أستيقظ في السادسة.', breakdown: [['I', 'أنا'], ['wake up', 'أستيقظ'], ['at six', 'في السادسة']] },
        { en: 'We work every day.', ar: 'نعمل كل يوم.' },
        { en: 'They study at night.', ar: 'هم يدرسون في الليل.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('wake up', 'get up', 'wash', 'work', 'study', 'sleep')),
      tryIt(mcq('a1-rou-try', 'I ___ English every day.', ['study', 'studies', 'studying'], 0, { pattern: 'present-simple' })),
      practice(T('Mini practice', 'تمرين صغير'),
        fill('a1-rou-1', 'We ___ at eight. (work)', ['work'], 'نعمل في الثامنة.', { pattern: 'present-simple' }),
        enAr('a1-rou-2', 'sleep', ['ينام', 'يغسل', 'يعمل'], 0),
        arEn('a1-rou-3', 'يستيقظ', ['wake up', 'get up', 'wash'], 0),
        wordOrder('a1-rou-4', ['English', 'I', 'study'], 'I study English', 'أدرس الإنجليزية', undefined, { pattern: 'present-simple' }),
        listenType('a1-rou-5', 'I get up at seven.', ['I get up at seven']),
        mcq('a1-rou-6', 'They ___ at night.', ['sleep', 'sleeps'], 0, { pattern: 'present-simple' }),
        sentenceOrder('a1-rou-7', ['I wake up at six.', 'I eat breakfast.', 'I go to work.', 'I sleep at night.'], 'Put the day in order.'),
      ),
      summary(T('Habits use the base verb with I / you / we / they.', 'العادات تستخدم الفعل الأصلي مع I / you / we / they.')),
    ],
  },
  {
    id: 'a1-he-she-s',
    title: T('He works, she studies', 'He works / she studies'),
    summary: T('Add -s with he, she and it.', 'أضف -s مع he و she و it.'),
    minutes: 9,
    skills: ['grammar'],
    vocab: W('cook', 'play', 'watch', 'listen', 'speak', 'walk', 'run', 'live'),
    grammarId: 'g-present-simple',
    steps: [
      explain(T('The -s rule', 'قاعدة -s'),
        T('With he, she and it, add -s to the verb: he works, she plays. Arabic does not do this, so it is an easy mistake.', 'مع he و she و it أضف -s إلى الفعل: he works و she plays. العربية لا تفعل ذلك، لذلك هو خطأ شائع.'),
        T('Verbs ending in -ch, -sh, -s, -x add -es: watch → watches. Consonant + y becomes -ies: study → studies.', 'الأفعال المنتهية بـ -ch و -sh و -s و -x تأخذ -es: watch ← watches. وتتحول y بعد حرف ساكن إلى -ies: study ← studies.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'He works in a bank.', ar: 'هو يعمل في بنك.' },
        { en: 'She watches TV.', ar: 'هي تشاهد التلفاز.' },
        { en: 'My brother plays football.', ar: 'أخي يلعب كرة القدم.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('cook', 'play', 'watch', 'listen', 'speak', 'walk', 'run', 'live')),
      tryIt(mcq('a1-s-try', 'She ___ English.', ['speak', 'speaks'], 1, { pattern: 'present-simple' })),
      practice(T('Mini practice', 'تمرين صغير'),
        mcq('a1-s-1', 'He ___ to school.', ['walk', 'walks'], 1, { pattern: 'present-simple' }),
        fill('a1-s-2', 'She ___ TV every night. (watch)', ['watches'], 'هي تشاهد التلفاز كل ليلة.', { pattern: 'present-simple' }),
        fix('a1-s-3', 'He play football.', ['He plays football'], { pattern: 'present-simple', explain: T('Add -s after he.', 'أضف -s بعد he.') }),
        fix('a1-s-4', 'My mother cook dinner.', ['My mother cooks dinner'], { pattern: 'present-simple' }),
        enAr('a1-s-5', 'live', ['يعيش', 'يجري', 'يسمع'], 0),
        wordOrder('a1-s-6', ['lives', 'He', 'here'], 'He lives here', 'هو يعيش هنا', undefined, { pattern: 'present-simple' }),
      ),
      summary(T('he / she / it + verb-s.', 'he / she / it + فعل مع s.'), T('watch → watches, study → studies.', 'watch ← watches و study ← studies.')),
    ],
  },
  {
    id: 'a1-do-does',
    title: T("I don't, he doesn't, do you?", 'النفي والسؤال: do / does'),
    summary: T('Make negatives and questions.', 'كوّن النفي والأسئلة.'),
    minutes: 10,
    skills: ['grammar'],
    vocab: W('know', 'think', 'love', 'like', 'want'),
    grammarId: 'g-do-does',
    steps: [
      explain(T('Helper verbs', 'الأفعال المساعدة'),
        T('For negatives use don\'t (I, you, we, they) or doesn\'t (he, she, it). For questions start with Do or Does. The main verb goes back to its base form.', 'للنفي استخدم don\'t مع I و you و we و they، و doesn\'t مع he و she و it. وللسؤال ابدأ بـ Do أو Does. ويعود الفعل الأساسي إلى صورته الأصلية.')),
      examples(T('See it', 'شاهدها'), [
        { en: "I don't know.", ar: 'لا أعرف.' },
        { en: 'She doesn\'t like coffee.', ar: 'هي لا تحب القهوة.' },
        { en: 'Do you speak English?', ar: 'هل تتحدث الإنجليزية؟' },
        { en: 'Does he work here?', ar: 'هل يعمل هنا؟' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('know', 'think', 'love', 'like', 'want')),
      tryIt(mcq('a1-do-try', 'She ___ like tea.', ["don't", "doesn't"], 1, { pattern: 'do-does' })),
      practice(T('Mini practice', 'تمرين صغير'),
        mcq('a1-do-1', '___ you like coffee?', ['Do', 'Does'], 0, { pattern: 'do-does' }),
        mcq('a1-do-2', '___ he work here?', ['Do', 'Does'], 1, { pattern: 'do-does' }),
        fix('a1-do-3', 'She doesn\'t likes tea.', ["She doesn't like tea"], { pattern: 'do-does', explain: T('After doesn\'t the verb has no -s.', 'بعد doesn\'t لا يأخذ الفعل -s.') }),
        fix('a1-do-4', 'Do he know you?', ['Does he know you'], { pattern: 'do-does' }),
        wordOrder('a1-do-5', ['you', 'Do', 'English', 'speak'], 'Do you speak English', 'هل تتحدث الإنجليزية؟', undefined, { pattern: 'do-does' }),
        fill('a1-do-6', 'I ___ want tea. (negative)', ["don't", 'do not'], 'لا أريد الشاي.', { pattern: 'do-does' }),
        tf('a1-do-7', '"He doesn\'t works" is correct.', false, { pattern: 'do-does' }),
      ),
      summary(T("Negative: don't / doesn't + base verb.", "النفي: don't / doesn't + الفعل الأصلي."), T('Question: Do / Does + subject + base verb?', 'السؤال: Do / Does + الفاعل + الفعل الأصلي؟')),
    ],
  },
  {
    id: 'a1-wh',
    title: T('Question words', 'كلمات الاستفهام'),
    summary: T('What, where, who, how.', 'what و where و who و how.'),
    minutes: 8,
    skills: ['grammar', 'vocab'],
    vocab: W('what', 'where', 'who', 'how', 'live', 'work'),
    grammarId: 'g-wh',
    steps: [
      explain(T('Ask for information', 'اسأل عن المعلومات'),
        T('Put the question word first, then do / does or am / is / are: Where do you live? What is your name?', 'ضع كلمة الاستفهام أولا ثم do / does أو am / is / are: Where do you live? What is your name?')),
      examples(T('See it', 'شاهدها'), [
        { en: 'Where do you live?', ar: 'أين تعيش؟' },
        { en: 'Who is he?', ar: 'من هو؟' },
        { en: 'How are you?', ar: 'كيف حالك؟' },
        { en: 'What do you study?', ar: 'ماذا تدرس؟' },
      ]),
      tryIt(chooseWord('a1-wh-try', '___ do you live? In Cairo.', ['Where', 'Who', 'What'], 0, { pattern: 'question-word' })),
      practice(T('Mini practice', 'تمرين صغير'),
        chooseWord('a1-wh-1', '___ is your teacher? Mr. Khan.', ['Who', 'Where', 'How'], 0, { pattern: 'question-word' }),
        chooseWord('a1-wh-2', '___ do you work? In a bank.', ['What', 'Where', 'Who'], 1, { pattern: 'question-word' }),
        wordOrder('a1-wh-3', ['do', 'live', 'Where', 'you'], 'Where do you live', 'أين تعيش؟', undefined, { pattern: 'question-word' }),
        wordOrder('a1-wh-4', ['is', 'she', 'Who'], 'Who is she', 'من هي؟', undefined, { pattern: 'question-word' }),
        enAr('a1-wh-5', 'who', ['من', 'أين', 'كيف'], 0),
        listenType('a1-wh-6', 'Where do you work?', ['Where do you work']),
      ),
      summary(T('Question word + do / does + subject + verb.', 'كلمة الاستفهام + do / does + الفاعل + الفعل.')),
    ],
  },
  {
    id: 'a1-days',
    title: T('Days of the week', 'أيام الأسبوع'),
    summary: T('Say when things happen.', 'قل متى تحدث الأشياء.'),
    minutes: 7,
    skills: ['vocab', 'listening'],
    vocab: W('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'week', 'time'),
    steps: [
      explain(T('On + day', 'on + اليوم'), T('Use on before a day: on Monday, on Friday. Days always start with a capital letter in English.', 'استخدم on قبل اليوم: on Monday و on Friday. وتبدأ الأيام دائما بحرف كبير في الإنجليزية.')),
      pronounce(T('Listen and repeat', 'استمع وكرر'), [
        { en: 'Monday, Tuesday, Wednesday', ar: 'الاثنين، الثلاثاء، الأربعاء' },
        { en: 'Thursday, Friday', ar: 'الخميس، الجمعة' },
        { en: 'Saturday, Sunday', ar: 'السبت، الأحد' },
      ]),
      examples(T('See it', 'شاهدها'), [
        { en: 'I work on Monday.', ar: 'أعمل يوم الاثنين.' },
        { en: 'There are seven days in a week.', ar: 'في الأسبوع سبعة أيام.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'week', 'time')),
      tryIt(complete('a1-day-try', 'Choose the correct word.', 'I go to school ___ Monday.', ['in', 'on', 'at'], 1, { pattern: 'preposition' })),
      practice(T('Mini practice', 'تمرين صغير'),
        matching('a1-day-1', [['Monday', 'الاثنين'], ['Friday', 'الجمعة'], ['Saturday', 'السبت'], ['Sunday', 'الأحد']]),
        enAr('a1-day-2', 'Thursday', ['الخميس', 'الأربعاء', 'الثلاثاء'], 0),
        arEn('a1-day-3', 'أسبوع', ['week', 'year', 'time'], 0),
        listenChoose('a1-day-4', 'Wednesday', 'Which day do you hear?', ['Tuesday', 'Wednesday', 'Thursday'], 1),
        fill('a1-day-5', 'I rest ___ Friday.', ['on'], 'أرتاح يوم الجمعة.', { pattern: 'preposition' }),
      ),
      summary(T('on + day: on Monday.', 'on + اليوم: on Monday.'), T('Days start with a capital letter.', 'الأيام تبدأ بحرف كبير.')),
    ],
  },
  {
    id: 'a1-frequency',
    title: T('Always, usually, sometimes, never', 'always / usually / sometimes / never'),
    summary: T('Say how often.', 'قل كم مرة.'),
    minutes: 8,
    skills: ['grammar', 'vocab'],
    vocab: W('always', 'usually', 'sometimes', 'never', 'tomorrow', 'yesterday', 'year'),
    grammarId: 'g-present-simple',
    steps: [
      explain(T('Frequency words', 'كلمات التكرار'),
        T('These words go BEFORE the main verb: I always drink tea. But AFTER am / is / are: She is always late.', 'تأتي هذه الكلمات قبل الفعل الأساسي: I always drink tea. ولكن بعد am / is / are: She is always late.'),
        T('From most to least: always, usually, sometimes, never.', 'من الأكثر إلى الأقل: always ثم usually ثم sometimes ثم never.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I always drink tea.', ar: 'أشرب الشاي دائما.' },
        { en: 'He usually walks to work.', ar: 'هو يمشي عادة إلى العمل.' },
        { en: 'We sometimes eat out.', ar: 'نأكل خارج البيت أحيانا.' },
        { en: 'They never sleep late.', ar: 'هم لا ينامون متأخرين أبدا.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('always', 'usually', 'sometimes', 'never', 'tomorrow', 'yesterday')),
      tryIt(chooseSentence('a1-fr-try', 'Which is correct?', ['I drink always tea.', 'I always drink tea.', 'Always I drink tea.'], 1, { pattern: 'word-order' })),
      practice(T('Mini practice', 'تمرين صغير'),
        enAr('a1-fr-1', 'sometimes', ['دائما', 'أحيانا', 'أبدا'], 1),
        enAr('a1-fr-2', 'never', ['أبدا', 'عادة', 'دائما'], 0),
        wordOrder('a1-fr-3', ['always', 'I', 'tea', 'drink'], 'I always drink tea', 'أشرب الشاي دائما', undefined, { pattern: 'word-order' }),
        fix('a1-fr-4', 'She goes always to school.', ['She always goes to school'], { pattern: 'word-order', explain: T('Put always before the verb.', 'ضع always قبل الفعل.') }),
        arEn('a1-fr-5', 'غدا', ['yesterday', 'tomorrow', 'today'], 1),
        tf('a1-fr-6', '"Never" means 100% of the time.', false),
      ),
      summary(T('always → usually → sometimes → never.', 'always ثم usually ثم sometimes ثم never.'), T('Place them before the main verb.', 'ضعها قبل الفعل الأساسي.')),
    ],
  },
  {
    id: 'a1-meals',
    title: T('Meals and food', 'الوجبات والطعام'),
    summary: T('Talk about what you eat each day.', 'تحدث عما تأكله كل يوم.'),
    minutes: 8,
    skills: ['vocab', 'listening'],
    vocab: W('breakfast', 'lunch', 'dinner', 'rice', 'chicken', 'vegetable', 'fruit', 'coffee', 'juice', 'hungry', 'thirsty'),
    steps: [
      explain(T('Meals', 'الوجبات'), T('We say have breakfast, have lunch, have dinner. We do not use a or the with meals.', 'نقول have breakfast و have lunch و have dinner. ولا نستخدم a أو the مع الوجبات.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I have breakfast at seven.', ar: 'أتناول الفطور في السابعة.' },
        { en: 'We eat rice and chicken for lunch.', ar: 'نأكل الأرز والدجاج في الغداء.' },
        { en: 'I am hungry.', ar: 'أنا جائع.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('breakfast', 'lunch', 'dinner', 'rice', 'chicken', 'vegetable', 'fruit', 'coffee', 'juice', 'hungry', 'thirsty')),
      tryIt(chooseWord('a1-meal-try', 'I am ___. I want water.', ['hungry', 'thirsty'], 1)),
      practice(T('Mini practice', 'تمرين صغير'),
        matching('a1-meal-1', [['rice', 'أرز'], ['chicken', 'دجاج'], ['juice', 'عصير'], ['fruit', 'فاكهة']]),
        enAr('a1-meal-2', 'dinner', ['العشاء', 'الغداء', 'الفطور'], 0),
        arEn('a1-meal-3', 'خضار', ['vegetable', 'fruit', 'rice'], 0),
        listenChoose('a1-meal-4', 'I drink coffee in the morning.', 'What do I drink?', ['tea', 'coffee', 'juice'], 1),
        fill('a1-meal-5', 'I have ___ at seven in the morning. (first meal)', ['breakfast'], 'أتناول الفطور في السابعة صباحا.'),
        recall('a1-meal-6', 'جائع', ['hungry'], 'w-hungry'),
      ),
      summary(T('have breakfast / lunch / dinner.', 'have breakfast / lunch / dinner.'), T('hungry = جائع, thirsty = عطشان.', 'hungry = جائع و thirsty = عطشان.')),
    ],
  },
  {
    id: 'a1-want-need',
    title: T('I want, I need', 'أريد وأحتاج'),
    summary: T('Ask for what you need.', 'اطلب ما تحتاجه.'),
    minutes: 8,
    skills: ['vocab', 'grammar'],
    vocab: W('want', 'need', 'buy', 'give', 'take', 'help', 'open', 'close'),
    steps: [
      explain(T('Polite requests', 'الطلب بأدب'), T('I want and I need are direct. To be polite say: Can you help me, please? or I would like water, please.', 'I want و I need مباشرتان. ولتكون مؤدبا قل: Can you help me, please? أو I would like water, please.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I need help.', ar: 'أحتاج إلى مساعدة.' },
        { en: 'I want to buy a book.', ar: 'أريد أن أشتري كتابا.' },
        { en: 'Can you open the door, please?', ar: 'هل يمكنك فتح الباب من فضلك؟' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('want', 'need', 'buy', 'give', 'take', 'help', 'open', 'close')),
      tryIt(chooseWord('a1-want-try', 'I ___ to buy bread.', ['want', 'wants'], 0)),
      practice(T('Mini practice', 'تمرين صغير'),
        enAr('a1-want-1', 'need', ['يحتاج', 'يريد', 'يشتري'], 0),
        arEn('a1-want-2', 'يفتح', ['close', 'open', 'take'], 1),
        wordOrder('a1-want-3', ['to', 'I', 'want', 'buy', 'milk'], 'I want to buy milk', 'أريد أن أشتري حليبا'),
        fill('a1-want-4', 'Can you ___ the window, please? (close)', ['close'], 'هل يمكنك إغلاق النافذة؟'),
        listenType('a1-want-5', 'I need help.', ['I need help']),
        fix('a1-want-6', 'She want a book.', ['She wants a book'], { pattern: 'present-simple' }),
      ),
      summary(T('I want / I need + noun, or want to + verb.', 'I want / I need + اسم، أو want to + فعل.'), T('Add please to sound polite.', 'أضف please لتبدو مؤدبا.')),
    ],
  },
  {
    id: 'a1-places',
    title: T('Places in the city', 'الأماكن في المدينة'),
    summary: T('Name places and say where you go.', 'سمّ الأماكن وقل إلى أين تذهب.'),
    minutes: 8,
    skills: ['vocab', 'reading'],
    vocab: W('city', 'street', 'shop', 'market', 'hospital', 'bank', 'park', 'go', 'live'),
    steps: [
      explain(T('Go to a place', 'الذهاب إلى مكان'), T('We say go to the bank, go to the market. But we say go home (no to).', 'نقول go to the bank و go to the market. ولكن نقول go home بدون to.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I live in a big city.', ar: 'أعيش في مدينة كبيرة.' },
        { en: 'The bank is on this street.', ar: 'البنك في هذا الشارع.' },
        { en: 'We go to the park on Friday.', ar: 'نذهب إلى الحديقة يوم الجمعة.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('city', 'street', 'shop', 'market', 'hospital', 'bank', 'park')),
      tryIt(complete('a1-pl-try', 'Choose the correct word.', 'I go ___ the market.', ['to', 'at', 'in'], 0, { pattern: 'preposition' })),
      practice(T('Mini practice', 'تمرين صغير'),
        matching('a1-pl-1', [['city', 'مدينة'], ['street', 'شارع'], ['hospital', 'مستشفى'], ['park', 'حديقة']]),
        enAr('a1-pl-2', 'bank', ['بنك', 'سوق', 'متجر'], 0),
        arEn('a1-pl-3', 'سوق', ['market', 'shop', 'park'], 0),
        fill('a1-pl-4', 'She goes ___ the hospital.', ['to'], 'هي تذهب إلى المستشفى.', { pattern: 'preposition' }),
        chooseSentence('a1-pl-5', 'Which is correct?', ['I go to home.', 'I go home.', 'I go at home.'], 1, { pattern: 'preposition' }),
        listenChoose('a1-pl-6', 'The shop is near the park.', 'Where is the shop?', ['near the park', 'in the bank', 'on the street'], 0),
      ),
      summary(T('go to + place, but go home.', 'go to + مكان، لكن go home.')),
    ],
  },
  {
    id: 'a1-prepositions',
    title: T('In, on, under, next to', 'in / on / under / next to'),
    summary: T('Say where things are.', 'قل أين توجد الأشياء.'),
    minutes: 9,
    skills: ['grammar', 'vocab'],
    vocab: W('in', 'on', 'under', 'next to', 'at', 'bag', 'table', 'chair', 'book'),
    grammarId: 'g-prepositions',
    steps: [
      explain(T('Place words', 'كلمات المكان'),
        T('in = inside. on = on top. under = below. next to = beside. at = at a point or place (at school, at home).', 'in = داخل. on = فوق وملامس. under = تحت. next to = بجانب. at = عند مكان أو نقطة (at school و at home).')),
      examples(T('See it', 'شاهدها'), [
        { en: 'The book is on the table.', ar: 'الكتاب على الطاولة.' },
        { en: 'The cat is under the chair.', ar: 'القطة تحت الكرسي.' },
        { en: 'My bag is next to the door.', ar: 'حقيبتي بجانب الباب.' },
        { en: 'I am at school.', ar: 'أنا في المدرسة.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('in', 'on', 'under', 'next to', 'at')),
      tryIt(complete('a1-pre-try', 'Choose the correct word.', 'The pen is ___ the bag.', ['in', 'on', 'under'], 0, { pattern: 'preposition' })),
      practice(T('Mini practice', 'تمرين صغير'),
        complete('a1-pre-1', 'Choose the correct word.', 'The book is ___ the table. (on top)', ['in', 'on', 'under'], 1, { pattern: 'preposition' }),
        complete('a1-pre-2', 'Choose the correct word.', 'The cat is ___ the chair. (below)', ['on', 'next to', 'under'], 2, { pattern: 'preposition' }),
        fill('a1-pre-3', 'I am ___ home.', ['at'], 'أنا في البيت.', { pattern: 'preposition' }),
        enAr('a1-pre-4', 'next to', ['بجانب', 'تحت', 'فوق'], 0),
        wordOrder('a1-pre-5', ['is', 'The', 'on', 'book', 'table', 'the'], 'The book is on the table', 'الكتاب على الطاولة', undefined, { pattern: 'preposition' }),
        listenChoose('a1-pre-6', 'The cat is under the table.', 'Where is the cat?', ['on the table', 'under the table', 'in the bag'], 1),
      ),
      summary(T('in = inside, on = on top, under = below, next to = beside.', 'in داخل و on فوق و under تحت و next to بجانب.')),
    ],
  },
  {
    id: 'a1-home',
    title: T('My home', 'بيتي'),
    summary: T('Describe the rooms in your home.', 'صف غرف بيتك.'),
    minutes: 8,
    skills: ['vocab', 'reading'],
    vocab: W('kitchen', 'bedroom', 'bathroom', 'window', 'bed', 'house', 'room', 'big', 'small'),
    steps: [
      explain(T('There is / There are', 'There is / There are'), T('Use there is for one thing and there are for many things: There is a bed. There are two windows.', 'استخدم there is لشيء واحد و there are لعدة أشياء: There is a bed. There are two windows.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'There is a kitchen in my house.', ar: 'يوجد مطبخ في بيتي.' },
        { en: 'There are two windows in the room.', ar: 'يوجد نافذتان في الغرفة.' },
        { en: 'My bedroom is small.', ar: 'غرفة نومي صغيرة.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('kitchen', 'bedroom', 'bathroom', 'window', 'bed')),
      tryIt(mcq('a1-home-try', '___ a bed in my room.', ['There is', 'There are'], 0)),
      practice(T('Mini practice', 'تمرين صغير'),
        mcq('a1-home-1', '___ two windows in the kitchen.', ['There is', 'There are'], 1),
        enAr('a1-home-2', 'bathroom', ['حمام', 'مطبخ', 'غرفة نوم'], 0),
        arEn('a1-home-3', 'نافذة', ['window', 'door', 'bed'], 0),
        matching('a1-home-4', [['kitchen', 'مطبخ'], ['bedroom', 'غرفة نوم'], ['bed', 'سرير'], ['window', 'نافذة']]),
        fix('a1-home-5', 'There is three beds.', ['There are three beds'], { explain: T('Three beds is plural, so use there are.', 'beds جمع لذلك نستخدم there are.') }),
        listenType('a1-home-6', 'My bedroom is small.', ['My bedroom is small']),
      ),
      summary(T('There is + one thing. There are + many things.', 'There is لشيء واحد و There are لأشياء كثيرة.')),
    ],
  },
  {
    id: 'a1-have-got',
    title: T('I have, she has', 'I have / she has'),
    summary: T('Talk about what you own.', 'تحدث عما تملكه.'),
    minutes: 8,
    skills: ['grammar', 'vocab'],
    vocab: W('have', 'phone', 'computer', 'car', 'bus', 'money'),
    grammarId: 'g-have-got',
    steps: [
      explain(T('Have and has', 'have و has'), T('Use have with I, you, we, they. Use has with he, she, it.', 'استخدم have مع I و you و we و they. واستخدم has مع he و she و it.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I have a phone.', ar: 'عندي هاتف.' },
        { en: 'She has a car.', ar: 'هي تملك سيارة.' },
        { en: 'We have a computer.', ar: 'عندنا حاسوب.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('phone', 'computer', 'car', 'bus', 'money')),
      tryIt(mcq('a1-have-try', 'He ___ a car.', ['have', 'has'], 1, { pattern: 'have' })),
      practice(T('Mini practice', 'تمرين صغير'),
        mcq('a1-have-1', 'They ___ a computer.', ['have', 'has'], 0, { pattern: 'have' }),
        fill('a1-have-2', 'My brother ___ a phone.', ['has'], 'أخي عنده هاتف.', { pattern: 'have' }),
        fix('a1-have-3', 'She have a bus ticket.', ['She has a bus ticket'], { pattern: 'have' }),
        enAr('a1-have-4', 'money', ['مال', 'سيارة', 'هاتف'], 0),
        arEn('a1-have-5', 'حاسوب', ['phone', 'computer', 'bus'], 1),
        wordOrder('a1-have-6', ['has', 'She', 'a', 'phone'], 'She has a phone', 'هي عندها هاتف', undefined, { pattern: 'have' }),
      ),
      summary(T('I / you / we / they have. He / she / it has.', 'I / you / we / they have و he / she / it has.')),
    ],
  },
  {
    id: 'a1-body',
    title: T('Parts of the body', 'أجزاء الجسم'),
    summary: T('Name body parts and say what hurts.', 'سمّ أجزاء الجسم وقل ما يؤلمك.'),
    minutes: 7,
    skills: ['vocab', 'listening'],
    vocab: W('head', 'hand', 'eye', 'ear', 'mouth', 'foot'),
    steps: [
      explain(T('Irregular plurals', 'جموع شاذة'), T('One foot, two feet. One eye, two eyes. Some plurals do not just add -s.', 'foot ثم feet و eye ثم eyes. بعض الجموع لا تكتفي بإضافة -s.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I have two hands.', ar: 'عندي يدان.' },
        { en: 'My head hurts.', ar: 'رأسي يؤلمني.' },
        { en: 'Open your mouth.', ar: 'افتح فمك.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('head', 'hand', 'eye', 'ear', 'mouth', 'foot')),
      tryIt(complete('a1-body-try', 'Choose the correct plural.', 'I have two ___.', ['foots', 'feet'], 1, { pattern: 'plural' })),
      practice(T('Mini practice', 'تمرين صغير'),
        matching('a1-body-1', [['head', 'رأس'], ['hand', 'يد'], ['eye', 'عين'], ['ear', 'أذن']]),
        enAr('a1-body-2', 'mouth', ['فم', 'قدم', 'رأس'], 0),
        arEn('a1-body-3', 'قدم', ['hand', 'foot', 'ear'], 1),
        fix('a1-body-4', 'I have two foots.', ['I have two feet'], { pattern: 'plural' }),
        listenChoose('a1-body-5', 'Open your eyes.', 'What do I open?', ['ears', 'eyes', 'hands'], 1),
        tf('a1-body-6', 'The plural of "foot" is "foots".', false, { pattern: 'plural' }),
      ),
      summary(T('foot → feet is irregular.', 'foot ← feet جمع شاذ.')),
    ],
  },
  {
    id: 'a1-adjectives',
    title: T('Describing people and things', 'وصف الأشخاص والأشياء'),
    summary: T('Tall, busy, tired, easy and more.', 'tall و busy و tired و easy وغيرها.'),
    minutes: 8,
    skills: ['vocab', 'grammar'],
    vocab: W('tall', 'short', 'young', 'beautiful', 'busy', 'tired', 'easy', 'difficult', 'fast', 'slow', 'near', 'far'),
    grammarId: 'g-be',
    steps: [
      explain(T('Opposites', 'الأضداد'), T('Learn adjectives in pairs: tall / short, easy / difficult, fast / slow, near / far.', 'تعلّم الصفات في أزواج: tall / short و easy / difficult و fast / slow و near / far.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'My brother is tall.', ar: 'أخي طويل.' },
        { en: 'The test is easy.', ar: 'الاختبار سهل.' },
        { en: 'I am tired today.', ar: 'أنا متعب اليوم.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('tall', 'short', 'young', 'beautiful', 'busy', 'tired', 'easy', 'difficult', 'fast', 'slow', 'near', 'far')),
      tryIt(arEn('a1-adj-try', 'سهل', ['easy', 'difficult', 'slow'], 0)),
      practice(T('Mini practice', 'تمرين صغير'),
        matching('a1-adj-1', [['tall', 'طويل'], ['fast', 'سريع'], ['near', 'قريب'], ['far', 'بعيد']]),
        enAr('a1-adj-2', 'beautiful', ['جميل', 'متعب', 'مشغول'], 0),
        fill('a1-adj-3', 'The car is ___. It is not slow. (fast)', ['fast'], 'السيارة سريعة.'),
        mcq('a1-adj-4', 'The opposite of "difficult" is ___.', ['easy', 'busy', 'tall'], 0, { skill: 'vocab' }),
        fill('a1-adj-5', 'She ___ busy today.', ['is'], 'هي مشغولة اليوم.', { pattern: 'be-verb' }),
        listenType('a1-adj-6', 'My brother is tall.', ['My brother is tall']),
      ),
      summary(T('Learn opposites together.', 'تعلّم الأضداد معا.'), T('Use am / is / are before adjectives.', 'استخدم am / is / are قبل الصفات.')),
    ],
  },
  {
    id: 'a1-connectors',
    title: T('And, but, because', 'and / but / because'),
    summary: T('Join ideas into longer sentences.', 'اربط الأفكار في جمل أطول.'),
    minutes: 8,
    skills: ['grammar', 'writing'],
    vocab: W('and', 'but', 'because', 'tired', 'happy'),
    steps: [
      explain(T('Linking words', 'كلمات الربط'),
        T('and adds an idea. but shows a contrast. because gives a reason.', 'and تضيف فكرة و but تُظهر تعارضا و because تعطي سببا.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I like tea and coffee.', ar: 'أحب الشاي والقهوة.' },
        { en: 'I like tea, but I do not like coffee.', ar: 'أحب الشاي لكني لا أحب القهوة.' },
        { en: 'I am tired because I work a lot.', ar: 'أنا متعب لأنني أعمل كثيرا.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('and', 'but', 'because')),
      tryIt(chooseWord('a1-con-try', 'I am happy ___ it is Friday.', ['and', 'but', 'because'], 2)),
      practice(T('Mini practice', 'تمرين صغير'),
        chooseWord('a1-con-1', 'I like fish ___ I do not like chicken.', ['and', 'but', 'because'], 1),
        chooseWord('a1-con-2', 'I have a pen ___ a book.', ['and', 'but', 'because'], 0),
        fill('a1-con-3', 'I stay home ___ I am tired.', ['because'], 'أبقى في البيت لأنني متعب.'),
        wordOrder('a1-con-4', ['tired', 'I', 'am', 'but', 'happy'], 'I am tired but happy', 'أنا متعب لكن سعيد'),
        enAr('a1-con-5', 'because', ['لأن', 'لكن', 'و'], 0),
        written('a1-con-6', 'Write one sentence with "because".', ['because'], 'I am happy because it is Friday.', [['because']]),
      ),
      summary(T('and = add, but = contrast, because = reason.', 'and للإضافة و but للتعارض و because للسبب.')),
    ],
  },
  {
    id: 'a1-weekend',
    title: T('Talk about your week', 'تحدث عن أسبوعك'),
    summary: T('Combine everything from A1.', 'اجمع كل ما تعلمته في A1.'),
    minutes: 10,
    skills: ['grammar', 'reading', 'writing'],
    vocab: W('week', 'always', 'usually', 'sometimes', 'never', 'study', 'work', 'play'),
    grammarId: 'g-present-simple',
    steps: [
      explain(T('Put it together', 'اجمع كل شيء'), T('Now you can describe a week: who you are, what you do, when and how often. Try to use because and but too.', 'الآن تستطيع وصف أسبوع كامل: من أنت وماذا تفعل ومتى وكم مرة. جرّب استخدام because و but أيضا.')),
      examples(T('Model', 'نموذج'), [
        { en: 'I usually work on Monday and Tuesday.', ar: 'أعمل عادة يومي الاثنين والثلاثاء.' },
        { en: 'On Friday I sometimes play football.', ar: 'يوم الجمعة ألعب كرة القدم أحيانا.' },
        { en: 'I never study on Saturday because I am tired.', ar: 'لا أدرس أبدا يوم السبت لأنني متعب.' },
      ]),
      tryIt(chooseSentence('a1-wk-try', 'Which is correct?', ['I usually play football on Friday.', 'I play usually football on Friday.'], 0, { pattern: 'word-order' })),
      practice(T('Mini practice', 'تمرين صغير'),
        fix('a1-wk-1', 'He never study on Friday.', ['He never studies on Friday'], { pattern: 'present-simple' }),
        wordOrder('a1-wk-2', ['on', 'work', 'I', 'usually', 'Monday'], 'I usually work on Monday', 'أعمل عادة يوم الاثنين', undefined, { pattern: 'word-order' }),
        fill('a1-wk-3', 'We ___ play football on Friday. (sometimes)', ['sometimes'], 'نلعب كرة القدم أحيانا يوم الجمعة.'),
        listenType('a1-wk-4', 'I never work on Friday.', ['I never work on Friday']),
        written('a1-wk-5', 'Write about your week. Use "usually".', ['usually'], 'I usually work on Monday and I study at night.', [['usually', 'always', 'sometimes']]),
      ),
      summary(T('You can now talk about your week at A1 level.', 'أصبحت تستطيع الحديث عن أسبوعك بمستوى A1.'), T('Next: A2 — the past and the future.', 'التالي: A2 — الماضي والمستقبل.')),
    ],
  },
]);
