import {
  T, W, levelLessons, explain, examples, vocabStep, tryIt, practice, summary,
  mcq, enAr, arEn, chooseWord, complete, fill, fix, tf, wordOrder, matching, listenChoose, listenType, written,
} from '../build';

export const A2_LESSONS = levelLessons('a2', [
  {
    id: 'a2-past-regular',
    title: T('Yesterday I visited…', 'أمس زرت…'),
    summary: T('Regular verbs in the past simple.', 'الأفعال المنتظمة في الماضي البسيط.'),
    minutes: 10,
    skills: ['grammar', 'vocab'],
    vocab: W('visit', 'invite', 'carry', 'enjoy', 'yesterday', 'together'),
    grammarId: 'g-past-simple',
    steps: [
      explain(T('Add -ed', 'أضف -ed'),
        T('For finished actions in the past, add -ed to regular verbs: visit → visited, enjoy → enjoyed. If the verb ends in -e add only -d: invite → invited.', 'للأحداث المنتهية في الماضي أضف -ed للأفعال المنتظمة: visit ← visited و enjoy ← enjoyed. وإذا انتهى الفعل بـ e أضف d فقط: invite ← invited.'),
        T('The form is the same for every person: I visited, she visited, they visited.', 'الصيغة نفسها لكل الأشخاص: I visited و she visited و they visited.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I visited my neighbor yesterday.', ar: 'زرت جاري أمس.' },
        { en: 'We enjoyed the meeting.', ar: 'استمتعنا بالاجتماع.' },
        { en: 'She invited me to dinner.', ar: 'دعتني إلى العشاء.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('visit', 'invite', 'carry', 'enjoy', 'together')),
      tryIt(mcq('a2-pr-try', 'Yesterday I ___ my friend.', ['visit', 'visited', 'visits'], 1, { pattern: 'past-simple' })),
      practice(T('Mini practice', 'تمرين صغير'),
        fill('a2-pr-1', 'We ___ the party. (enjoy)', ['enjoyed'], 'استمتعنا بالحفلة.', { pattern: 'past-simple' }),
        fill('a2-pr-2', 'She ___ her brother to dinner. (invite)', ['invited'], 'دعت أخاها إلى العشاء.', { pattern: 'past-simple' }),
        fix('a2-pr-3', 'I visit my uncle yesterday.', ['I visited my uncle yesterday'], { pattern: 'past-simple', explain: T('Yesterday needs the past form.', 'yesterday تحتاج صيغة الماضي.') }),
        wordOrder('a2-pr-4', ['visited', 'yesterday', 'I', 'her'], 'I visited her yesterday', 'زرتها أمس', undefined, { pattern: 'past-simple' }),
        listenType('a2-pr-5', 'They carried the bags together.', ['They carried the bags together']),
        enAr('a2-pr-6', 'invite', ['يدعو', 'يزور', 'يحمل'], 0),
      ),
      summary(T('Regular past: verb + -ed (or -d).', 'الماضي المنتظم: فعل + ed أو d.'), T('Same form for every person.', 'الصيغة نفسها لكل الأشخاص.')),
    ],
  },
  {
    id: 'a2-past-irregular',
    title: T('Went, saw, had', 'went / saw / had'),
    summary: T('Common irregular verbs.', 'أفعال شاذة شائعة.'),
    minutes: 10,
    skills: ['grammar'],
    vocab: W('go', 'see', 'have', 'eat', 'buy', 'take', 'forget', 'remember'),
    grammarId: 'g-past-simple',
    steps: [
      explain(T('Irregular verbs', 'الأفعال الشاذة'),
        T('Some verbs change completely: go → went, see → saw, have → had, eat → ate, buy → bought, take → took. You must learn them.', 'بعض الأفعال تتغير تماما: go ← went و see ← saw و have ← had و eat ← ate و buy ← bought و take ← took. عليك حفظها.'),
        T('For negatives and questions use did + base verb: I did not go. Did you see him?', 'للنفي والسؤال استخدم did + الفعل الأصلي: I did not go. Did you see him?')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I went to the market.', ar: 'ذهبت إلى السوق.' },
        { en: 'She bought a new phone.', ar: 'اشترت هاتفا جديدا.' },
        { en: 'Did you see the doctor?', ar: 'هل رأيت الطبيب؟' },
        { en: 'We did not eat lunch.', ar: 'لم نتناول الغداء.' },
      ]),
      tryIt(mcq('a2-pi-try', 'Last week I ___ to the hotel.', ['go', 'went', 'goed'], 1, { pattern: 'past-simple' })),
      practice(T('Mini practice', 'تمرين صغير'),
        matching('a2-pi-1', [['go', 'went'], ['see', 'saw'], ['buy', 'bought'], ['eat', 'ate']]),
        fill('a2-pi-2', 'He ___ a ticket yesterday. (buy)', ['bought'], 'اشترى تذكرة أمس.', { pattern: 'past-simple' }),
        fix('a2-pi-3', 'I goed to school.', ['I went to school'], { pattern: 'past-simple' }),
        fix('a2-pi-4', 'Did you saw him?', ['Did you see him'], { pattern: 'past-simple', explain: T('After did use the base verb.', 'بعد did نستخدم الفعل الأصلي.') }),
        mcq('a2-pi-5', 'Yesterday, we ___ not eat breakfast.', ['did', 'do', 'ate'], 0, { pattern: 'past-simple' }),
        listenChoose('a2-pi-6', 'I forgot my passport.', 'What did I forget?', ['my ticket', 'my passport', 'my bag'], 1),
      ),
      summary(T('go → went, see → saw, buy → bought, eat → ate.', 'go ← went و see ← saw و buy ← bought و eat ← ate.'), T('Negative/question: did + base verb.', 'النفي والسؤال: did + الفعل الأصلي.')),
    ],
  },
  {
    id: 'a2-comparatives',
    title: T('Bigger, better, more expensive', 'أكبر وأفضل وأغلى'),
    summary: T('Compare two things.', 'قارن بين شيئين.'),
    minutes: 9,
    skills: ['grammar', 'vocab'],
    vocab: W('expensive', 'cheap', 'comfortable', 'dangerous', 'important', 'delicious'),
    grammarId: 'g-comparatives',
    steps: [
      explain(T('Comparing', 'المقارنة'),
        T('Short adjectives add -er + than: tall → taller than. Long adjectives use more … than: expensive → more expensive than.', 'الصفات القصيرة تأخذ -er + than: tall ← taller than. والصفات الطويلة تستخدم more … than: expensive ← more expensive than.'),
        T('Irregular: good → better, bad → worse.', 'شاذة: good ← better و bad ← worse.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'This car is cheaper than that car.', ar: 'هذه السيارة أرخص من تلك.' },
        { en: 'The hotel is more comfortable than my house.', ar: 'الفندق أكثر راحة من بيتي.' },
        { en: 'Today is better than yesterday.', ar: 'اليوم أفضل من أمس.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('expensive', 'cheap', 'comfortable', 'dangerous', 'important', 'delicious')),
      tryIt(mcq('a2-cmp-try', 'A plane is ___ than a bus.', ['fast', 'faster', 'more fast'], 1, { pattern: 'comparative' })),
      practice(T('Mini practice', 'تمرين صغير'),
        fill('a2-cmp-1', 'This phone is ___ than that one. (cheap)', ['cheaper'], 'هذا الهاتف أرخص من ذاك.', { pattern: 'comparative' }),
        complete('a2-cmp-2', 'Choose the correct form.', 'The hotel is ___ than the airport.', ['more comfortable', 'comfortabler', 'most comfortable'], 0, { pattern: 'comparative' }),
        fix('a2-cmp-3', 'My house is more big than yours.', ['My house is bigger than yours'], { pattern: 'comparative' }),
        mcq('a2-cmp-4', 'This food is ___ than that food. (good)', ['gooder', 'better', 'more good'], 1, { pattern: 'comparative' }),
        enAr('a2-cmp-5', 'dangerous', ['خطير', 'رخيص', 'مريح'], 0),
        tf('a2-cmp-6', '"More expensive" is a correct comparative.', true, { pattern: 'comparative' }),
      ),
      summary(T('short + -er than, long → more … than.', 'قصير + er than وطويل ← more … than.'), T('good → better, bad → worse.', 'good ← better و bad ← worse.')),
    ],
  },
  {
    id: 'a2-future',
    title: T('Plans: going to and will', 'الخطط: going to و will'),
    summary: T('Talk about the future.', 'تحدث عن المستقبل.'),
    minutes: 9,
    skills: ['grammar'],
    vocab: W('travel', 'ticket', 'airport', 'hotel', 'passport', 'luggage', 'maybe'),
    grammarId: 'g-future',
    steps: [
      explain(T('Two ways', 'طريقتان'),
        T('going to = a plan you already made: I am going to travel next week.', 'going to = خطة قررتها من قبل: I am going to travel next week.'),
        T('will = a quick decision or a prediction: It will rain. I will help you.', 'will = قرار سريع أو توقع: It will rain. I will help you.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I am going to visit Dubai.', ar: 'سأزور دبي (خطة).' },
        { en: 'She is going to buy a ticket.', ar: 'ستشتري تذكرة.' },
        { en: 'Maybe it will rain tomorrow.', ar: 'ربما تمطر غدا.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('travel', 'ticket', 'airport', 'hotel', 'passport', 'luggage', 'maybe')),
      tryIt(mcq('a2-fut-try', 'I ___ to travel next week.', ['am going', 'go', 'went'], 0, { pattern: 'future' })),
      practice(T('Mini practice', 'تمرين صغير'),
        fill('a2-fut-1', 'He is ___ to buy a ticket.', ['going'], 'سيشتري تذكرة.', { pattern: 'future' }),
        mcq('a2-fut-2', 'The phone is ringing. I ___ answer it.', ['will', 'am going', 'did'], 0, { pattern: 'future' }),
        wordOrder('a2-fut-3', ['going', 'We', 'to', 'are', 'travel'], 'We are going to travel', 'سنسافر', undefined, { pattern: 'future' }),
        fix('a2-fut-4', 'She going to visit the hotel.', ['She is going to visit the hotel'], { pattern: 'future', explain: T('Do not forget is.', 'لا تنسَ is.') }),
        enAr('a2-fut-5', 'luggage', ['أمتعة', 'جواز سفر', 'مطار'], 0),
        listenType('a2-fut-6', 'I am going to travel tomorrow.', ['I am going to travel tomorrow', "I'm going to travel tomorrow"]),
      ),
      summary(T('be going to + verb = plan.', 'be going to + فعل = خطة.'), T('will + verb = decision or prediction.', 'will + فعل = قرار أو توقع.')),
    ],
  },
  {
    id: 'a2-weather',
    title: T('Weather and feelings', 'الطقس والمشاعر'),
    summary: T('Describe the weather and say what you prefer.', 'صف الطقس وقل ما تفضله.'),
    minutes: 8,
    skills: ['vocab', 'reading'],
    vocab: W('weather', 'rain', 'sunny', 'cloudy', 'prefer', 'enjoy'),
    steps: [
      explain(T('It is…', 'It is…'), T('For weather we use it: It is sunny. It is cloudy. It rains a lot here. Use prefer … to … to compare likes.', 'للطقس نستخدم it: It is sunny. It is cloudy. It rains a lot here. واستخدم prefer … to … للمقارنة بين ما نحب.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'It is sunny today.', ar: 'الجو مشمس اليوم.' },
        { en: 'I prefer tea to coffee.', ar: 'أفضل الشاي على القهوة.' },
        { en: 'What is the weather like?', ar: 'كيف حال الطقس؟' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('weather', 'rain', 'sunny', 'cloudy', 'prefer')),
      tryIt(chooseWord('a2-w-try', '___ is sunny today.', ['It', 'He', 'There'], 0)),
      practice(T('Mini practice', 'تمرين صغير'),
        matching('a2-w-1', [['sunny', 'مشمس'], ['cloudy', 'غائم'], ['rain', 'مطر'], ['weather', 'طقس']]),
        listenChoose('a2-w-2', 'It is cloudy and cold today.', 'How is the weather?', ['sunny and hot', 'cloudy and cold', 'rainy'], 1),
        fill('a2-w-3', 'I ___ tea to coffee. (like more)', ['prefer'], 'أفضل الشاي على القهوة.'),
        arEn('a2-w-4', 'مطر', ['rain', 'sunny', 'weather'], 0),
        written('a2-w-5', 'Write about the weather today.', ['it is'], 'It is sunny and warm today.', [['sunny', 'cloudy', 'rain', 'hot', 'cold', 'warm']]),
      ),
      summary(T('It is + weather word.', 'It is + كلمة الطقس.'), T('prefer A to B.', 'prefer A to B.')),
    ],
  },
  {
    id: 'a2-work',
    title: T('At work', 'في العمل'),
    summary: T('Meetings, messages and appointments.', 'الاجتماعات والرسائل والمواعيد.'),
    minutes: 9,
    skills: ['vocab', 'listening'],
    vocab: W('manager', 'customer', 'meeting', 'appointment', 'message', 'problem', 'idea', 'quickly', 'carefully'),
    steps: [
      explain(T('Adverbs of manner', 'ظروف الطريقة'), T('Add -ly to an adjective to say how: quick → quickly, careful → carefully. They usually go after the verb or the object.', 'أضف -ly إلى الصفة لتقول كيف: quick ← quickly و careful ← carefully. وتأتي عادة بعد الفعل أو المفعول.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'The manager has a meeting at ten.', ar: 'عند المدير اجتماع في العاشرة.' },
        { en: 'Please read the message carefully.', ar: 'من فضلك اقرأ الرسالة بعناية.' },
        { en: 'We have a problem, but I have an idea.', ar: 'لدينا مشكلة لكن عندي فكرة.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('manager', 'customer', 'meeting', 'appointment', 'message', 'problem', 'idea', 'quickly', 'carefully')),
      tryIt(complete('a2-wk-try', 'Choose the correct form.', 'She works ___.', ['careful', 'carefully'], 1)),
      practice(T('Mini practice', 'تمرين صغير'),
        enAr('a2-wk-1', 'customer', ['زبون', 'مدير', 'اجتماع'], 0),
        enAr('a2-wk-2', 'appointment', ['موعد', 'مشكلة', 'فكرة'], 0),
        fix('a2-wk-3', 'He drives careful.', ['He drives carefully'], { skill: 'grammar' }),
        listenType('a2-wk-4', 'I have a meeting with the manager.', ['I have a meeting with the manager']),
        arEn('a2-wk-5', 'رسالة', ['message', 'idea', 'problem'], 0),
        wordOrder('a2-wk-6', ['quickly', 'works', 'She'], 'She works quickly', 'هي تعمل بسرعة'),
      ),
      summary(T('adjective + -ly = how something is done.', 'صفة + ly = كيف يتم الفعل.')),
    ],
  },
]);
