import {
  T, W, levelLessons, explain, examples, vocabStep, tryIt, practice, summary,
  mcq, enAr, arEn, chooseWord, complete, fill, fix, tf, wordOrder, matching, listenType, written,
} from '../build';

export const B1_LESSONS = levelLessons('b1', [
  {
    id: 'b1-perfect',
    title: T('Have you ever…?', 'هل سبق أن…؟'),
    summary: T('Experiences with the present perfect.', 'التجارب بالمضارع التام.'),
    minutes: 11,
    skills: ['grammar', 'vocab'],
    vocab: W('experience', 'achieve', 'improve', 'manage', 'opportunity'),
    grammarId: 'g-present-perfect',
    steps: [
      explain(T('have / has + past participle', 'have / has + التصريف الثالث'),
        T('Use the present perfect for experiences without a finished time: I have visited Turkey. For he / she / it use has.', 'استخدم المضارع التام للتجارب دون وقت محدد منته: I have visited Turkey. ومع he / she / it استخدم has.'),
        T('Do not use it with yesterday or last year; use the past simple.', 'لا تستخدمه مع yesterday أو last year؛ استخدم الماضي البسيط.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I have worked here for two years.', ar: 'أعمل هنا منذ سنتين.' },
        { en: 'She has never travelled alone.', ar: 'لم تسافر وحدها قط.' },
        { en: 'Have you ever managed a team?', ar: 'هل سبق أن أدرت فريقا؟' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('experience', 'achieve', 'improve', 'manage', 'opportunity')),
      tryIt(mcq('b1-pf-try', 'I ___ never seen snow.', ['have', 'has', 'did'], 0, { pattern: 'present-perfect' })),
      practice(T('Mini practice', 'تمرين صغير'),
        mcq('b1-pf-1', 'She ___ achieved a lot.', ['have', 'has', 'is'], 1, { pattern: 'present-perfect' }),
        fill('b1-pf-2', 'We have ___ our English. (improve)', ['improved'], 'لقد حسّنا إنجليزيتنا.', { pattern: 'present-perfect' }),
        fix('b1-pf-3', 'I have seen him yesterday.', ['I saw him yesterday'], { pattern: 'present-perfect', explain: T('With yesterday use the past simple.', 'مع yesterday نستخدم الماضي البسيط.') }),
        wordOrder('b1-pf-4', ['ever', 'you', 'Have', 'travelled'], 'Have you ever travelled', 'هل سبق أن سافرت؟', undefined, { pattern: 'present-perfect' }),
        tf('b1-pf-5', '"She have worked here" is correct.', false, { pattern: 'present-perfect' }),
        enAr('b1-pf-6', 'opportunity', ['فرصة', 'تجربة', 'نصيحة'], 0),
      ),
      summary(T('have / has + past participle for experiences.', 'have / has + التصريف الثالث للتجارب.'), T('No finished time word.', 'دون كلمة وقت منتهٍ.')),
    ],
  },
  {
    id: 'b1-conditionals',
    title: T('If it rains, I will stay home', 'If it rains, I will stay home'),
    summary: T('First conditional sentences.', 'الجملة الشرطية من النوع الأول.'),
    minutes: 10,
    skills: ['grammar'],
    vocab: W('prepare', 'depend', 'consider', 'accept', 'refuse', 'probably'),
    grammarId: 'g-conditionals',
    steps: [
      explain(T('If + present, will + verb', 'If + مضارع، will + فعل'),
        T('Use the first conditional for real possibilities in the future: If you study, you will pass. After if use the present simple, not will.', 'استخدم الشرط الأول للاحتمالات الحقيقية في المستقبل: If you study, you will pass. وبعد if نستخدم المضارع البسيط وليس will.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'If it rains, we will stay home.', ar: 'إذا أمطرت سنبقى في البيت.' },
        { en: 'I will accept the job if they offer more money.', ar: 'سأقبل الوظيفة إذا عرضوا مالا أكثر.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('prepare', 'depend', 'consider', 'accept', 'refuse', 'probably')),
      tryIt(mcq('b1-if-try', 'If she ___, she will pass.', ['studies', 'will study', 'studied'], 0, { pattern: 'conditional' })),
      practice(T('Mini practice', 'تمرين صغير'),
        fill('b1-if-1', 'If I ___ early, I will help you. (finish)', ['finish'], 'إذا أنهيت مبكرا سأساعدك.', { pattern: 'conditional' }),
        fix('b1-if-2', 'If it will rain, we will stay.', ['If it rains, we will stay'], { pattern: 'conditional', explain: T('No will after if.', 'لا نستخدم will بعد if.') }),
        complete('b1-if-3', 'Choose the correct word.', 'If you prepare well, you ___ succeed.', ['will', 'would', 'did'], 0, { pattern: 'conditional' }),
        wordOrder('b1-if-4', ['If', 'rains', 'it', 'we', 'will', 'stay'], 'If it rains we will stay', 'إذا أمطرت سنبقى', ['If it rains, we will stay'], { pattern: 'conditional' }),
        enAr('b1-if-5', 'refuse', ['يرفض', 'يقبل', 'يعتمد'], 0),
        listenType('b1-if-6', 'If you help me, I will help you.', ['If you help me I will help you']),
      ),
      summary(T('If + present simple, will + base verb.', 'If + مضارع بسيط، will + فعل أصلي.')),
    ],
  },
  {
    id: 'b1-opinions',
    title: T('Giving opinions', 'إبداء الرأي'),
    summary: T('Although, however and therefore.', 'although و however و therefore.'),
    minutes: 10,
    skills: ['grammar', 'writing', 'vocab'],
    vocab: W('although', 'however', 'therefore', 'actually', 'advice', 'suggest', 'avoid', 'compare', 'describe'),
    steps: [
      explain(T('Linking opinions', 'ربط الآراء'),
        T('although = even if (inside one sentence). however = contrast, starts a new sentence. therefore = result.', 'although = مع أن (داخل جملة واحدة). however = تعارض وتبدأ جملة جديدة. therefore = نتيجة.'),
        T('To give an opinion: I think that…, In my opinion…, I suggest…', 'لإبداء الرأي: I think that… و In my opinion… و I suggest…')),
      examples(T('See it', 'شاهدها'), [
        { en: 'Although it is expensive, I like it.', ar: 'مع أنه غالٍ إلا أنني أحبه.' },
        { en: 'It is cheap. However, it is not good.', ar: 'إنه رخيص، لكنه ليس جيدا.' },
        { en: 'I was tired, therefore I slept early.', ar: 'كنت متعبا لذلك نمت مبكرا.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('although', 'however', 'therefore', 'actually', 'advice', 'suggest', 'avoid', 'compare', 'describe')),
      tryIt(chooseWord('b1-op-try', '___ it was raining, we went out.', ['Although', 'Therefore', 'However'], 0)),
      practice(T('Mini practice', 'تمرين صغير'),
        chooseWord('b1-op-1', 'He studied hard. ___, he passed.', ['Although', 'Therefore', 'But if'], 1),
        chooseWord('b1-op-2', 'The hotel is nice. ___, it is expensive.', ['However', 'Because', 'And'], 0),
        enAr('b1-op-3', 'advice', ['نصيحة', 'فرصة', 'مشكلة'], 0),
        arEn('b1-op-4', 'يتجنب', ['avoid', 'suggest', 'accept'], 0),
        matching('b1-op-5', [['suggest', 'يقترح'], ['compare', 'يقارن'], ['describe', 'يصف'], ['avoid', 'يتجنب']]),
        written('b1-op-6', 'Give your opinion about learning English. Use "I think".', ['i think'], 'I think learning English is important because it opens many opportunities.', [['think', 'opinion'], ['because', 'therefore', 'however']]),
      ),
      summary(T('although (same sentence), however (new sentence), therefore (result).', 'although في الجملة نفسها و however بجملة جديدة و therefore للنتيجة.')),
    ],
  },
  {
    id: 'b1-society',
    title: T('Society and environment', 'المجتمع والبيئة'),
    summary: T('Vocabulary for discussions.', 'مفردات للنقاشات.'),
    minutes: 9,
    skills: ['vocab', 'reading'],
    vocab: W('environment', 'government', 'society', 'responsible', 'successful', 'confident', 'available', 'necessary', 'organize', 'article'),
    steps: [
      explain(T('Abstract words', 'كلمات مجردة'), T('Many B1 words end in -ment, -ty, -ful. Notice endings: govern → government, success → successful.', 'كثير من كلمات B1 تنتهي بـ -ment و -ty و -ful. لاحظ النهايات: govern ← government و success ← successful.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'We are responsible for the environment.', ar: 'نحن مسؤولون عن البيئة.' },
        { en: 'The government organized a big meeting.', ar: 'نظمت الحكومة اجتماعا كبيرا.' },
        { en: 'Is this article available online?', ar: 'هل هذا المقال متاح على الإنترنت؟' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('environment', 'government', 'society', 'responsible', 'successful', 'confident', 'available', 'necessary', 'organize', 'article')),
      tryIt(enAr('b1-soc-try', 'government', ['حكومة', 'مجتمع', 'بيئة'], 0)),
      practice(T('Mini practice', 'تمرين صغير'),
        matching('b1-soc-1', [['environment', 'بيئة'], ['society', 'مجتمع'], ['article', 'مقال'], ['necessary', 'ضروري']]),
        arEn('b1-soc-2', 'واثق', ['confident', 'successful', 'available'], 0),
        fill('b1-soc-3', 'She is very ___ in her job. (got good results)', ['successful'], 'هي ناجحة جدا في عملها.'),
        listenType('b1-soc-4', 'We must protect the environment.', ['We must protect the environment']),
        tf('b1-soc-5', '"Responsible" means "مسؤول".', true),
        mcq('b1-soc-6', 'I need to ___ my notes before the exam.', ['organize', 'refuse', 'avoid'], 0, { skill: 'vocab' }),
      ),
      summary(T('Notice word endings: -ment, -ful, -ty.', 'لاحظ نهايات الكلمات: -ment و -ful و -ty.')),
    ],
  },
]);
