import {
  T, W, levelLessons, explain, examples, vocabStep, tryIt, practice, summary,
  mcq, enAr, arEn, chooseWord, fill, fix, tf, wordOrder, matching, listenType, written,
} from '../build';

export const B2_LESSONS = levelLessons('b2', [
  {
    id: 'b2-passive',
    title: T('It was built in 1990', 'المبني للمجهول'),
    summary: T('The passive voice.', 'صيغة المبني للمجهول.'),
    minutes: 11,
    skills: ['grammar'],
    vocab: W('establish', 'regulation', 'consequence', 'evidence', 'considerable'),
    grammarId: 'g-passive',
    steps: [
      explain(T('be + past participle', 'be + التصريف الثالث'),
        T('Use the passive when the action matters more than who did it: The company was established in 1990. Add by + agent only if needed.', 'نستخدم المبني للمجهول عندما يهم الفعل أكثر من فاعله: The company was established in 1990. وأضف by + الفاعل عند الحاجة فقط.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'The rules are explained in the book.', ar: 'تُشرح القواعد في الكتاب.' },
        { en: 'The bridge was built in 1990.', ar: 'بُني الجسر عام 1990.' },
        { en: 'New regulations will be introduced.', ar: 'ستُطبَّق أنظمة جديدة.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('establish', 'regulation', 'consequence', 'evidence', 'considerable')),
      tryIt(mcq('b2-pas-try', 'The letter ___ yesterday.', ['was sent', 'sent', 'is send'], 0, { pattern: 'passive' })),
      practice(T('Mini practice', 'تمرين صغير'),
        mcq('b2-pas-1', 'English ___ all over the world.', ['is spoken', 'speaks', 'spoke'], 0, { pattern: 'passive' }),
        fix('b2-pas-2', 'The house built in 1980.', ['The house was built in 1980'], { pattern: 'passive', explain: T('Add was before the participle.', 'أضف was قبل التصريف الثالث.') }),
        fill('b2-pas-3', 'The company was ___ in 1995. (establish)', ['established'], 'تأسست الشركة عام 1995.', { pattern: 'passive' }),
        wordOrder('b2-pas-4', ['was', 'The', 'built', 'bridge', 'in', '1990'], 'The bridge was built in 1990', 'بُني الجسر عام 1990', undefined, { pattern: 'passive' }),
        enAr('b2-pas-5', 'consequence', ['نتيجة', 'دليل', 'نظام'], 0),
        listenType('b2-pas-6', 'The rules were changed.', ['The rules were changed']),
      ),
      summary(T('Passive = be + past participle.', 'المبني للمجهول = be + التصريف الثالث.')),
    ],
  },
  {
    id: 'b2-reported',
    title: T('She said that…', 'الكلام المنقول'),
    summary: T('Report what people said.', 'انقل ما قاله الآخرون.'),
    minutes: 11,
    skills: ['grammar', 'writing'],
    vocab: W('acknowledge', 'emphasize', 'assume', 'reluctant', 'currently', 'approximately'),
    grammarId: 'g-reported',
    steps: [
      explain(T('Step back in time', 'خطوة إلى الماضي'),
        T('When we report speech, the verb usually moves one step back: "I am tired" → She said (that) she was tired. "I will come" → He said he would come.', 'عند نقل الكلام يرجع الفعل عادة خطوة إلى الماضي: "I am tired" ← She said (that) she was tired. و "I will come" ← He said he would come.'),
        T('Pronouns and time words change too: today → that day, tomorrow → the next day.', 'وتتغير الضمائر وكلمات الزمن أيضا: today ← that day و tomorrow ← the next day.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'He said that he was busy.', ar: 'قال إنه مشغول.' },
        { en: 'She said she would call me.', ar: 'قالت إنها ستتصل بي.' },
        { en: 'They acknowledged that there was a problem.', ar: 'أقروا بوجود مشكلة.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('acknowledge', 'emphasize', 'assume', 'reluctant', 'currently', 'approximately')),
      tryIt(mcq('b2-rep-try', '"I am happy." → She said she ___ happy.', ['was', 'is', 'will be'], 0, { pattern: 'reported-speech' })),
      practice(T('Mini practice', 'تمرين صغير'),
        mcq('b2-rep-1', '"I will help." → He said he ___ help.', ['would', 'will', 'did'], 0, { pattern: 'reported-speech' }),
        fix('b2-rep-2', 'She said that she is tired yesterday.', ['She said that she was tired yesterday'], { pattern: 'reported-speech' }),
        arEn('b2-rep-3', 'تقريبا', ['approximately', 'currently', 'reluctant'], 0),
        enAr('b2-rep-4', 'reluctant', ['متردد', 'حاليا', 'يفترض'], 0),
        tf('b2-rep-5', 'In reported speech "tomorrow" often becomes "the next day".', true, { pattern: 'reported-speech' }),
        written('b2-rep-6', 'Report this: "I am busy." (Start with "He said")', ['he said'], 'He said that he was busy.', [['said'], ['was']]),
      ),
      summary(T('Reported speech steps the verb back.', 'الكلام المنقول يرجع بالفعل خطوة إلى الماضي.')),
    ],
  },
  {
    id: 'b2-linking',
    title: T('Nuance and linking', 'الدقة والربط'),
    summary: T('Nevertheless, furthermore, whereas.', 'nevertheless و furthermore و whereas.'),
    minutes: 10,
    skills: ['vocab', 'writing', 'reading'],
    vocab: W('nevertheless', 'furthermore', 'whereas', 'perspective', 'attitude', 'contribute', 'sustainable', 'inequality', 'overcome', 'inevitable', 'deliberately', 'significant', 'struggle', 'recover', 'assume'),
    steps: [
      explain(T('Advanced connectors', 'أدوات ربط متقدمة'),
        T('furthermore adds a point. nevertheless means "in spite of that". whereas compares two facts.', 'furthermore تضيف نقطة. nevertheless بمعنى "رغم ذلك". whereas تقارن بين حقيقتين.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'The plan is risky. Nevertheless, we will try.', ar: 'الخطة محفوفة بالمخاطر؛ ومع ذلك سنحاول.' },
        { en: 'He likes cities, whereas she prefers villages.', ar: 'هو يحب المدن بينما تفضل هي القرى.' },
        { en: 'Furthermore, it is sustainable.', ar: 'وعلاوة على ذلك فهو مستدام.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('nevertheless', 'furthermore', 'whereas', 'perspective', 'attitude', 'contribute', 'sustainable', 'inequality', 'overcome', 'inevitable', 'deliberately', 'significant', 'struggle', 'recover')),
      tryIt(chooseWord('b2-lnk-try', 'He is rich, ___ she is poor.', ['whereas', 'furthermore', 'nevertheless'], 0)),
      practice(T('Mini practice', 'تمرين صغير'),
        chooseWord('b2-lnk-1', 'It is cheap. ___, it is also fast.', ['Furthermore', 'Whereas', 'Although'], 0),
        matching('b2-lnk-2', [['sustainable', 'مستدام'], ['inequality', 'عدم المساواة'], ['attitude', 'موقف'], ['perspective', 'منظور']]),
        enAr('b2-lnk-3', 'overcome', ['يتغلب على', 'يسترد', 'يساهم'], 0),
        arEn('b2-lnk-4', 'مهم بشكل ملحوظ', ['significant', 'inevitable', 'deliberately'], 0),
        listenType('b2-lnk-5', 'Nevertheless, we continued.', ['Nevertheless we continued']),
        mcq('b2-lnk-6', 'It is ___ that prices will rise. (cannot be avoided)', ['inevitable', 'reluctant', 'sustainable'], 0, { skill: 'vocab' }),
      ),
      summary(T('furthermore = add, nevertheless = in spite of, whereas = compare.', 'furthermore للإضافة و nevertheless رغم ذلك و whereas للمقارنة.')),
    ],
  },
]);
