import {
  T, W, levelLessons, explain, examples, pronounce, vocabStep, tryIt, practice, summary,
  mcq, enAr, arEn, chooseWord, chooseSentence, complete, fill, fix, tf, recall, wordOrder, matching, listenChoose, listenType,
} from '../build';

export const STARTER_LESSONS = levelLessons('starter', [
  {
    id: 'st-greetings',
    title: T('Hello! Greetings', 'مرحبا! التحيات'),
    summary: T('Say hello and goodbye politely.', 'قل مرحبا وإلى اللقاء بأدب.'),
    minutes: 6,
    skills: ['vocab', 'listening'],
    vocab: W('hello', 'goodbye', 'please', 'thank you', 'sorry', 'yes', 'no'),
    steps: [
      explain(T('Your first words', 'أولى كلماتك'),
        T('Greetings are the first thing you say to anyone. Good news: they are short and you will use them every day.', 'التحيات أول ما تقوله لأي شخص. وهي قصيرة وستستخدمها كل يوم.')),
      pronounce(T('Listen and repeat', 'استمع وكرر'), [
        { en: 'Hello!', ar: 'مرحبا!' },
        { en: 'Goodbye!', ar: 'إلى اللقاء!' },
        { en: 'Please.', ar: 'من فضلك.' },
        { en: 'Thank you.', ar: 'شكرا لك.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('hello', 'goodbye', 'please', 'thank you', 'sorry', 'yes', 'no')),
      examples(T('In use', 'في الاستخدام'), [
        { en: 'Hello, my name is Sam.', ar: 'مرحبا، اسمي سام.' },
        { en: 'Thank you for your help.', ar: 'شكرا لك على مساعدتك.' },
        { en: 'I am sorry.', ar: 'أنا آسف.' },
      ]),
      tryIt(enAr('st-greet-try', 'hello', ['مرحبا', 'إلى اللقاء', 'شكرا لك'], 0)),
      practice(T('Mini practice', 'تمرين صغير'),
        enAr('st-greet-1', 'goodbye', ['مرحبا', 'إلى اللقاء', 'آسف'], 1),
        arEn('st-greet-2', 'شكرا لك', ['sorry', 'please', 'thank you'], 2),
        chooseWord('st-greet-3', 'You want something politely. Which word do you add?', ['sorry', 'please', 'goodbye'], 1),
        listenChoose('st-greet-4', 'Thank you', 'What did you hear?', ['Hello', 'Thank you', 'Sorry'], 1),
        recall('st-greet-5', 'مرحبا', ['hello'], 'w-hello'),
      ),
      summary(
        T('hello = مرحبا, goodbye = إلى اللقاء.', 'hello = مرحبا و goodbye = إلى اللقاء.'),
        T('Add please to be polite, and thank you to show thanks.', 'أضف please للتأدب و thank you للشكر.'),
      ),
    ],
  },
  {
    id: 'st-name',
    title: T('My name is…', 'اسمي هو…'),
    summary: T('Introduce yourself.', 'عرّف بنفسك.'),
    minutes: 7,
    skills: ['vocab', 'grammar'],
    vocab: W('name', 'I', 'you', 'what', 'my', 'your'),
    grammarId: 'g-be',
    steps: [
      explain(T('Say your name', 'قل اسمك'),
        T('To tell someone your name, say "My name is …". To ask, say "What is your name?".', 'لتخبر شخصا باسمك قل "My name is …". وللسؤال قل "What is your name?".')),
      examples(T('Look at the pattern', 'انظر إلى النمط'), [
        { en: 'My name is Lina.', ar: 'اسمي لينا.', breakdown: [['My name', 'اسمي'], ['is', 'هو'], ['Lina', 'لينا']] },
        { en: 'What is your name?', ar: 'ما اسمك؟', breakdown: [['What', 'ما'], ['is', 'يكون'], ['your name', 'اسمك']] },
        { en: 'I am Sam.', ar: 'أنا سام.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('name', 'I', 'you', 'what', 'my', 'your')),
      tryIt(complete('st-name-try', 'Complete the sentence.', 'My ___ is Sam.', ['name', 'you', 'is'], 0)),
      practice(T('Mini practice', 'تمرين صغير'),
        wordOrder('st-name-1', ['is', 'My', 'name', 'Ali'], 'My name is Ali', 'اسمي علي'),
        wordOrder('st-name-2', ['your', 'is', 'What', 'name'], 'What is your name', 'ما اسمك؟'),
        fill('st-name-3', 'What is ___ name?', ['your'], 'ما اسمك؟'),
        arEn('st-name-4', 'أنا', ['you', 'I', 'he'], 1),
        listenType('st-name-5', 'My name is Sam.', ['My name is Sam']),
      ),
      summary(
        T('My name is … tells your name.', 'My name is … لتقول اسمك.'),
        T('What is your name? asks for a name.', 'What is your name? لتسأل عن الاسم.'),
      ),
    ],
  },
  {
    id: 'st-be',
    title: T('I am, you are, he is', 'I am / you are / he is'),
    summary: T('The most important English verb: to be.', 'أهم فعل في الإنجليزية: to be.'),
    minutes: 9,
    skills: ['grammar'],
    vocab: W('am', 'is', 'are', 'he', 'she', 'we', 'they', 'it'),
    grammarId: 'g-be',
    steps: [
      explain(T('English needs a verb', 'الإنجليزية تحتاج فعلا'),
        T('In Arabic you say "أنا مبرمج". In English you must say "I am a developer". The small word am is the verb.', 'في العربية تقول "أنا مبرمج". أما في الإنجليزية فيجب أن تقول "I am a developer". والكلمة الصغيرة am هي الفعل.'),
        T('I → am. he / she / it → is. you / we / they → are.', 'I ← am. و he / she / it ← is. و you / we / they ← are.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I am a student.', ar: 'أنا طالب.' },
        { en: 'She is a teacher.', ar: 'هي معلمة.' },
        { en: 'They are at home.', ar: 'هم في البيت.' },
        { en: 'It is a book.', ar: 'إنه كتاب.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('he', 'she', 'we', 'they', 'it', 'am', 'is', 'are')),
      tryIt(mcq('st-be-try', 'I ___ a student.', ['is', 'am', 'are'], 1, { pattern: 'be-verb', explain: T('I always goes with am.', 'الضمير I يأتي دائما مع am.') })),
      practice(T('Mini practice', 'تمرين صغير'),
        mcq('st-be-1', 'She ___ happy.', ['am', 'is', 'are'], 1, { pattern: 'be-verb' }),
        mcq('st-be-2', 'They ___ friends.', ['is', 'am', 'are'], 2, { pattern: 'be-verb' }),
        fill('st-be-3', 'We ___ at school.', ['are'], 'نحن في المدرسة.', { pattern: 'be-verb' }),
        fix('st-be-4', 'He are a doctor.', ['He is a doctor', "He's a doctor"], { pattern: 'be-verb', explain: T('He goes with is.', 'He تأتي مع is.') }),
        fix('st-be-5', 'I a student.', ['I am a student', "I'm a student"], { pattern: 'be-verb', explain: T('Do not forget the verb am.', 'لا تنس الفعل am.') }),
        wordOrder('st-be-6', ['am', 'I', 'happy'], 'I am happy', 'أنا سعيد', ["I'm happy"], { pattern: 'be-verb' }),
      ),
      summary(
        T('I am · you are · he / she / it is · we / you / they are.', 'I am · you are · he / she / it is · we / you / they are.'),
        T('Never drop the verb in English.', 'لا تحذف الفعل أبدا في الإنجليزية.'),
      ),
    ],
  },
  {
    id: 'st-numbers',
    title: T('Numbers 1–10', 'الأرقام من 1 إلى 10'),
    summary: T('Count and say how many.', 'عدّ وقل كم العدد.'),
    minutes: 6,
    skills: ['vocab', 'listening'],
    vocab: W('one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten'),
    steps: [
      explain(T('Count to ten', 'عد إلى عشرة'), T('Numbers are easy and very useful: age, time, price. Say each number aloud.', 'الأرقام سهلة ومفيدة: العمر والوقت والسعر. انطق كل رقم بصوت عال.')),
      pronounce(T('Listen and repeat', 'استمع وكرر'), [
        { en: 'one, two, three', ar: 'واحد، اثنان، ثلاثة' },
        { en: 'four, five, six', ar: 'أربعة، خمسة، ستة' },
        { en: 'seven, eight, nine, ten', ar: 'سبعة، ثمانية، تسعة، عشرة' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten')),
      tryIt(enAr('st-num-try', 'five', ['ثلاثة', 'خمسة', 'تسعة'], 1)),
      practice(T('Mini practice', 'تمرين صغير'),
        matching('st-num-1', [['one', 'واحد'], ['four', 'أربعة'], ['seven', 'سبعة'], ['ten', 'عشرة']]),
        arEn('st-num-2', 'ثمانية', ['six', 'eight', 'nine'], 1),
        listenChoose('st-num-3', 'seven', 'Which number do you hear?', ['six', 'seven', 'ten'], 1),
        listenType('st-num-4', 'nine', ['nine']),
        fill('st-num-5', 'I have ___ books. (2)', ['two'], 'عندي كتابان.'),
        recall('st-num-6', 'عشرة', ['ten'], 'w-ten'),
      ),
      summary(T('one to ten: one, two, three, four, five, six, seven, eight, nine, ten.', 'من واحد إلى عشرة: one … ten.')),
    ],
  },
  {
    id: 'st-colors',
    title: T('Colors', 'الألوان'),
    summary: T('Name colors and describe things.', 'سمّ الألوان وصف الأشياء.'),
    minutes: 6,
    skills: ['vocab', 'grammar'],
    vocab: W('red', 'blue', 'green', 'yellow', 'black', 'white', 'apple', 'bird'),
    steps: [
      explain(T('Adjectives before nouns', 'الصفة قبل الاسم'),
        T('In English the color comes BEFORE the noun: a red apple. In Arabic it comes after: تفاحة حمراء.', 'في الإنجليزية يأتي اللون قبل الاسم: a red apple. أما في العربية فبعده: تفاحة حمراء.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'a red apple', ar: 'تفاحة حمراء', breakdown: [['a', 'واحدة'], ['red', 'حمراء'], ['apple', 'تفاحة']] },
        { en: 'a blue bird', ar: 'طائر أزرق' },
        { en: 'The wall is white.', ar: 'الجدار أبيض.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('red', 'blue', 'green', 'yellow', 'black', 'white')),
      tryIt(chooseSentence('st-col-try', 'Which is correct?', ['a apple red', 'a red apple', 'red a apple'], 1, { pattern: 'word-order' })),
      practice(T('Mini practice', 'تمرين صغير'),
        matching('st-col-1', [['red', 'أحمر'], ['blue', 'أزرق'], ['green', 'أخضر'], ['yellow', 'أصفر']]),
        enAr('st-col-2', 'black', ['أبيض', 'أسود', 'أخضر'], 1),
        arEn('st-col-3', 'أبيض', ['white', 'blue', 'red'], 0),
        wordOrder('st-col-4', ['bird', 'blue', 'a'], 'a blue bird', 'طائر أزرق', undefined, { pattern: 'word-order' }),
        listenChoose('st-col-5', 'green', 'Which color do you hear?', ['red', 'green', 'yellow'], 1),
      ),
      summary(T('Color + noun: a red apple.', 'اللون + الاسم: a red apple.')),
    ],
  },
  {
    id: 'st-articles',
    title: T('A, an, the', 'a / an / the'),
    summary: T('Small words, big difference.', 'كلمات صغيرة بفرق كبير.'),
    minutes: 8,
    skills: ['grammar'],
    vocab: W('a', 'the', 'book', 'pen', 'apple', 'egg'),
    grammarId: 'g-articles',
    steps: [
      explain(T('One thing: a / an', 'شيء واحد: a / an'),
        T('Use a or an before ONE thing. Use an before a vowel sound: an apple, an egg. Use a before other sounds: a book, a pen.', 'استخدم a أو an قبل شيء واحد. استخدم an قبل الصوت المتحرك: an apple و an egg. و a قبل غيره: a book و a pen.'),
        T('Use the when you mean a specific thing: the pen on the table.', 'استخدم the عندما تقصد شيئا محددا: the pen on the table.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I have a pen.', ar: 'عندي قلم.' },
        { en: 'I eat an egg.', ar: 'آكل بيضة.' },
        { en: 'The pen is red.', ar: 'القلم أحمر.' },
      ]),
      tryIt(complete('st-art-try', 'Choose a or an.', 'I have ___ apple.', ['a', 'an'], 1, { pattern: 'article' })),
      practice(T('Mini practice', 'تمرين صغير'),
        complete('st-art-1', 'Choose a or an.', 'She has ___ book.', ['a', 'an'], 0, { pattern: 'article' }),
        complete('st-art-2', 'Choose a or an.', 'He eats ___ egg.', ['a', 'an'], 1, { pattern: 'article' }),
        fill('st-art-3', 'I am ___ student.', ['a'], 'أنا طالب.', { pattern: 'article' }),
        fix('st-art-4', 'I have a apple.', ['I have an apple'], { pattern: 'article', explain: T('Apple starts with a vowel sound.', 'كلمة apple تبدأ بصوت متحرك.') }),
        fix('st-art-5', 'She is teacher.', ['She is a teacher'], { pattern: 'article' }),
        tf('st-art-6', 'We say "an book".', false, { pattern: 'article' }),
      ),
      summary(T('a + consonant sound, an + vowel sound.', 'a قبل الصوت الساكن و an قبل المتحرك.'), T('Use the for a specific thing.', 'استخدم the للشيء المحدد.')),
    ],
  },
  {
    id: 'st-family',
    title: T('My family', 'عائلتي'),
    summary: T('Talk about the people close to you.', 'تحدث عن المقربين منك.'),
    minutes: 7,
    skills: ['vocab', 'grammar'],
    vocab: W('mother', 'father', 'brother', 'sister', 'friend', 'family', 'boy', 'girl'),
    steps: [
      explain(T('Family words', 'كلمات العائلة'), T('Use my before family words: my mother, my father. It means "ـي" in Arabic.', 'استخدم my قبل كلمات العائلة: my mother و my father. ومعناها "ـي" في العربية.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'This is my mother.', ar: 'هذه أمي.' },
        { en: 'He is my brother.', ar: 'هو أخي.' },
        { en: 'I love my family.', ar: 'أحب عائلتي.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('mother', 'father', 'brother', 'sister', 'friend', 'family')),
      tryIt(enAr('st-fam-try', 'sister', ['أخت', 'أخ', 'أم'], 0)),
      practice(T('Mini practice', 'تمرين صغير'),
        matching('st-fam-1', [['mother', 'أم'], ['father', 'أب'], ['brother', 'أخ'], ['sister', 'أخت']]),
        wordOrder('st-fam-2', ['is', 'my', 'He', 'brother'], 'He is my brother', 'هو أخي'),
        fill('st-fam-3', 'She is ___ sister.', ['my'], 'هي أختي.'),
        arEn('st-fam-4', 'صديق', ['friend', 'family', 'father'], 0),
        listenType('st-fam-5', 'This is my mother.', ['This is my mother']),
      ),
      summary(T('my + family word: my mother, my brother.', 'my + كلمة العائلة.')),
    ],
  },
  {
    id: 'st-this-that',
    title: T('This and that', 'هذا وذلك'),
    summary: T('Point at things near and far.', 'أشر إلى القريب والبعيد.'),
    minutes: 7,
    skills: ['grammar', 'vocab'],
    vocab: W('this', 'that', 'house', 'school', 'room', 'bag', 'table', 'chair', 'door'),
    grammarId: 'g-this-that',
    steps: [
      explain(T('Near and far', 'قريب وبعيد'), T('this is for something near you. that is for something far from you.', 'this للشيء القريب منك و that للشيء البعيد عنك.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'This is my bag.', ar: 'هذه حقيبتي.' },
        { en: 'That is my school.', ar: 'تلك مدرستي.' },
        { en: 'Is this your chair?', ar: 'هل هذا كرسيك؟' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('house', 'school', 'room', 'bag', 'table', 'chair', 'door')),
      tryIt(mcq('st-this-try', 'The door is far. Say: ___ is a door.', ['This', 'That'], 1, { pattern: 'demonstrative' })),
      practice(T('Mini practice', 'تمرين صغير'),
        mcq('st-this-1', 'My pen is in my hand. ___ is my pen.', ['This', 'That'], 0, { pattern: 'demonstrative' }),
        fill('st-this-2', '___ is my house. (far)', ['That'], 'ذلك بيتي.', { pattern: 'demonstrative' }),
        enAr('st-this-3', 'table', ['كرسي', 'طاولة', 'باب'], 1),
        arEn('st-this-4', 'غرفة', ['room', 'house', 'door'], 0),
        wordOrder('st-this-5', ['my', 'is', 'This', 'room'], 'This is my room', 'هذه غرفتي'),
      ),
      summary(T('this = near, that = far.', 'this للقريب و that للبعيد.')),
    ],
  },
  {
    id: 'st-food',
    title: T('Food and drink', 'الطعام والشراب'),
    summary: T('Say what you eat and drink.', 'قل ما تأكله وما تشربه.'),
    minutes: 7,
    skills: ['vocab', 'grammar'],
    vocab: W('water', 'bread', 'milk', 'apple', 'egg', 'tea', 'eat', 'drink', 'like'),
    steps: [
      explain(T('Eat and drink', 'يأكل ويشرب'), T('Use eat for food and drink for liquids. "I like tea" means "أحب الشاي".', 'استخدم eat للطعام و drink للسوائل. "I like tea" تعني "أحب الشاي".')),
      examples(T('See it', 'شاهدها'), [
        { en: 'I drink water.', ar: 'أشرب الماء.' },
        { en: 'I eat bread.', ar: 'آكل الخبز.' },
        { en: 'I like milk.', ar: 'أحب الحليب.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('water', 'bread', 'milk', 'apple', 'egg', 'tea', 'eat', 'drink', 'like')),
      tryIt(chooseWord('st-food-try', 'I ___ tea.', ['eat', 'drink'], 1)),
      practice(T('Mini practice', 'تمرين صغير'),
        chooseWord('st-food-1', 'I ___ bread.', ['eat', 'drink'], 0),
        enAr('st-food-2', 'milk', ['ماء', 'حليب', 'شاي'], 1),
        arEn('st-food-3', 'بيضة', ['egg', 'apple', 'bread'], 0),
        matching('st-food-4', [['water', 'ماء'], ['bread', 'خبز'], ['tea', 'شاي'], ['apple', 'تفاحة']]),
        fill('st-food-5', 'I ___ water every day.', ['drink'], 'أشرب الماء كل يوم.'),
        listenChoose('st-food-6', 'I like tea.', 'What do you like?', ['milk', 'tea', 'bread'], 1),
      ),
      summary(T('eat food, drink liquids, like = أحب.', 'eat للطعام و drink للسوائل و like = أحب.')),
    ],
  },
  {
    id: 'st-describe',
    title: T('Big, small, hot, cold', 'كبير وصغير وحار وبارد'),
    summary: T('Describe people and things.', 'صف الأشخاص والأشياء.'),
    minutes: 7,
    skills: ['vocab', 'grammar'],
    vocab: W('big', 'small', 'good', 'bad', 'happy', 'sad', 'hot', 'cold', 'new', 'old'),
    grammarId: 'g-be',
    steps: [
      explain(T('Adjectives with to be', 'الصفات مع to be'), T('Use am / is / are before an adjective: The tea is hot. I am happy.', 'استخدم am / is / are قبل الصفة: The tea is hot. I am happy.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'The house is big.', ar: 'البيت كبير.' },
        { en: 'The water is cold.', ar: 'الماء بارد.' },
        { en: 'I am happy.', ar: 'أنا سعيد.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('big', 'small', 'good', 'bad', 'happy', 'sad', 'hot', 'cold', 'new', 'old')),
      tryIt(mcq('st-desc-try', 'The tea ___ hot.', ['am', 'is', 'are'], 1, { pattern: 'be-verb' })),
      practice(T('Mini practice', 'تمرين صغير'),
        matching('st-desc-1', [['big', 'كبير'], ['small', 'صغير'], ['hot', 'حار'], ['cold', 'بارد']]),
        fill('st-desc-2', 'The cat ___ small.', ['is'], 'القطة صغيرة.', { pattern: 'be-verb' }),
        enAr('st-desc-3', 'sad', ['سعيد', 'حزين', 'جديد'], 1),
        arEn('st-desc-4', 'قديم', ['new', 'old', 'bad'], 1),
        tf('st-desc-5', '"Hot" means "بارد".', false),
        wordOrder('st-desc-6', ['is', 'big', 'The', 'house'], 'The house is big', 'البيت كبير'),
      ),
      summary(T('Subject + am / is / are + adjective.', 'الفاعل + am / is / are + صفة.')),
    ],
  },
  {
    id: 'st-animals',
    title: T('Animals and plurals', 'الحيوانات والجمع'),
    summary: T('One cat, two cats.', 'قطة واحدة وقطتان.'),
    minutes: 7,
    skills: ['vocab', 'grammar'],
    vocab: W('cat', 'dog', 'bird', 'fish', 'two', 'three'),
    grammarId: 'g-plural',
    steps: [
      explain(T('Add -s for more than one', 'أضف -s لأكثر من واحد'), T('One cat, two cats. One book, three books. Add -s to make most nouns plural.', 'cat ثم cats و book ثم books. أضف -s لتجمع معظم الأسماء.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'one cat, two cats', ar: 'قطة واحدة، قطتان' },
        { en: 'I have three birds.', ar: 'عندي ثلاثة طيور.' },
        { en: 'The dogs are big.', ar: 'الكلاب كبيرة.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('cat', 'dog', 'bird', 'fish')),
      tryIt(complete('st-ani-try', 'Choose the correct form.', 'I have two ___.', ['cat', 'cats'], 1, { pattern: 'plural' })),
      practice(T('Mini practice', 'تمرين صغير'),
        complete('st-ani-1', 'Choose the correct form.', 'She has three ___.', ['bird', 'birds'], 1, { pattern: 'plural' }),
        fix('st-ani-2', 'I have two dog.', ['I have two dogs'], { pattern: 'plural', explain: T('Use the plural after two.', 'استخدم الجمع بعد two.') }),
        enAr('st-ani-3', 'fish', ['سمكة', 'طائر', 'كلب'], 0),
        arEn('st-ani-4', 'قطة', ['dog', 'cat', 'bird'], 1),
        fill('st-ani-5', 'The ___ are big. (dog)', ['dogs'], 'الكلاب كبيرة.', { pattern: 'plural' }),
      ),
      summary(T('Add -s for plural: cat → cats.', 'أضف -s للجمع: cat ← cats.')),
    ],
  },
  {
    id: 'st-first-sentences',
    title: T('Your first sentences', 'جملك الأولى'),
    summary: T('Put it all together.', 'اجمع كل ما تعلمته.'),
    minutes: 9,
    skills: ['vocab', 'grammar', 'listening', 'writing'],
    vocab: W('have', 'go', 'read', 'write', 'see', 'morning', 'night', 'today', 'how', 'who', 'where'),
    steps: [
      explain(T('Build sentences', 'ابنِ الجمل'), T('Now you can say who you are, what you have and what you like. Use I + verb: I have a pen. I read a book.', 'الآن تستطيع أن تقول من أنت وما عندك وما تحب. استخدم I + فعل: I have a pen. I read a book.')),
      examples(T('See it', 'شاهدها'), [
        { en: 'Good morning! How are you?', ar: 'صباح الخير! كيف حالك؟' },
        { en: 'I am fine, thank you.', ar: 'أنا بخير، شكرا.' },
        { en: 'I go to school today.', ar: 'أذهب إلى المدرسة اليوم.' },
      ]),
      vocabStep(T('New words', 'كلمات جديدة'), W('have', 'go', 'read', 'write', 'see', 'morning', 'night', 'today', 'how', 'who', 'where')),
      tryIt(arEn('st-first-try', 'كيف', ['how', 'who', 'where'], 0)),
      practice(T('Mini practice', 'تمرين صغير'),
        wordOrder('st-first-1', ['a', 'have', 'I', 'pen'], 'I have a pen', 'عندي قلم'),
        wordOrder('st-first-2', ['read', 'I', 'book', 'a'], 'I read a book', 'أقرأ كتابا'),
        enAr('st-first-3', 'where', ['من', 'أين', 'كيف'], 1),
        listenType('st-first-4', 'How are you?', ['How are you']),
        fill('st-first-5', 'I ___ to school. (go)', ['go'], 'أذهب إلى المدرسة.'),
        listenChoose('st-first-6', 'Good night!', 'What did you hear?', ['Good morning', 'Good night', 'Goodbye'], 1),
      ),
      summary(T('You can now greet, introduce yourself, count and describe.', 'أصبحت تستطيع التحية والتعريف بنفسك والعد والوصف.'), T('Next: A1, where you talk about your day.', 'التالي: مستوى A1 حيث تتحدث عن يومك.')),
    ],
  },
]);
