import type { AchievementDef } from '@/types';

const A = (id: string, icon: string, title: [string, string], description: [string, string], xp: number, hidden = false): AchievementDef => ({
  id,
  icon,
  title: { en: title[0], ar: title[1] },
  description: { en: description[0], ar: description[1] },
  xp,
  hidden,
});

/** Conditions live in domain/achievements.ts, keyed by the same ids. */
export const ACHIEVEMENTS: AchievementDef[] = [
  A('first-answer', 'Sparkles', ['First Step', 'الخطوة الأولى'], ['Answer your first question.', 'أجب عن أول سؤال لك.'], 10),
  A('first-lesson', 'BookOpen', ['Curious Mind', 'عقل فضولي'], ['Complete your first lesson.', 'أكمل أول درس لك.'], 20),
  A('questions-50', 'Target', ['Warming Up', 'بداية الحماس'], ['Answer 50 questions.', 'أجب عن 50 سؤالًا.'], 25),
  A('questions-250', 'Flame', ['In the Groove', 'في الإيقاع'], ['Answer 250 questions.', 'أجب عن 250 سؤالًا.'], 60),
  A('questions-1000', 'Rocket', ['Thousand Club', 'نادي الألف'], ['Answer 1,000 questions.', 'أجب عن 1000 سؤال.'], 150),
  A('correct-100', 'CheckCheck', ['Century of Correct', 'مئة إجابة صحيحة'], ['Get 100 answers right.', 'احصل على 100 إجابة صحيحة.'], 50),
  A('streak-3', 'Flame', ['Three in a Row', 'ثلاثة أيام متتالية'], ['Practise 3 days in a row.', 'تدرّب 3 أيام متتالية.'], 20),
  A('streak-7', 'CalendarCheck', ['Week of Wonder', 'أسبوع متواصل'], ['Practise 7 days in a row.', 'تدرّب 7 أيام متتالية.'], 50),
  A('streak-30', 'CalendarHeart', ['Month of Mastery', 'شهر من الإتقان'], ['Practise 30 days in a row.', 'تدرّب 30 يومًا متتاليًا.'], 200),
  A('perfect-session', 'Medal', ['Flawless', 'بلا أخطاء'], ['Finish a practice session of 5+ questions without a mistake.', 'أنهِ جلسة تدريب من 5 أسئلة أو أكثر دون أي خطأ.'], 30),
  A('perfect-3', 'Award', ['Hat Trick', 'ثلاث جلسات مثالية'], ['Finish 3 flawless practice sessions.', 'أنهِ 3 جلسات تدريب بلا أخطاء.'], 80),
  A('no-hint-10', 'Brain', ['On My Own', 'بمفردي'], ['Answer 10 questions in a row right without hints.', 'أجب عن 10 أسئلة متتالية بشكل صحيح دون تلميحات.'], 40),
  A('no-hint-25', 'Lightbulb', ['Clear Thinker', 'تفكير صافٍ'], ['Answer 25 questions in a row right without hints.', 'أجب عن 25 سؤالًا متتاليًا بشكل صحيح دون تلميحات.'], 100),
  A('speedy-20', 'Zap', ['Quick Draw', 'سريع البديهة'], ['Get 20 answers right in under 4 seconds each.', 'أجب عن 20 سؤالًا بشكل صحيح في أقل من 4 ثوانٍ لكل منها.'], 40),
  A('timed-30', 'Timer', ['Beat the Clock', 'سباق مع الوقت'], ['Get 30 answers right in Timed mode.', 'أجب عن 30 سؤالًا بشكل صحيح في وضع الوقت.'], 50),
  A('lessons-10', 'Library', ['Student', 'طالب مجتهد'], ['Complete 10 lessons.', 'أكمل 10 دروس.'], 60),
  A('lessons-all', 'GraduationCap', ['Whole Curriculum', 'المنهج كاملًا'], ['Complete every lesson.', 'أكمل جميع الدروس.'], 400),
  A('three-stars', 'Star', ['Full Marks', 'علامة كاملة'], ['Earn three stars on a lesson.', 'احصل على ثلاث نجوم في درس.'], 25),
  A('level-1', 'Footprints', ['Foundations Done', 'أتممت الأساسيات'], ['Complete every lesson of Level 1.', 'أكمل جميع دروس المستوى الأول.'], 80),
  A('level-5', 'Sigma', ['Algebra Unlocked', 'فتحت الجبر'], ['Complete every lesson of Level 5.', 'أكمل جميع دروس المستوى الخامس.'], 150),
  A('mastery-first', 'Gem', ['First Mastery', 'أول إتقان'], ['Reach 81+ mastery in any topic.', 'بلغ 81 أو أكثر من الإتقان في أي موضوع.'], 60),
  A('mastery-5', 'Crown', ['Five Strong Topics', 'خمسة مواضيع قوية'], ['Reach 81+ mastery in five topics.', 'بلغ 81 أو أكثر من الإتقان في خمسة مواضيع.'], 150),
  A('exam-first', 'ClipboardCheck', ['Exam Taker', 'خضت اختبارًا'], ['Finish your first exam.', 'أنهِ أول اختبار لك.'], 30),
  A('exam-ace', 'Trophy', ['Top of the Class', 'الأول على الصف'], ['Score 90% or more on an exam of 10+ questions.', 'احصل على 90% أو أكثر في اختبار من 10 أسئلة أو أكثر.'], 100),
  A('daily-first', 'CalendarDays', ['Daily Challenger', 'متحدّي اليوم'], ['Complete a daily challenge.', 'أكمل تحدّي اليوم.'], 30),
  A('daily-7', 'Swords', ['Seven Challenges', 'سبعة تحديات'], ['Complete 7 daily challenges.', 'أكمل 7 تحديات يومية.'], 100),
  A('mistake-fixed', 'Wrench', ['Learning from Slips', 'أتعلّم من أخطائي'], ['Understand a saved mistake by getting it right on retry.', 'افهم خطأً محفوظًا بحلّه بشكل صحيح عند إعادته.'], 25),
  A('mistake-cleaner', 'Eraser', ['Clean Slate', 'صفحة نظيفة'], ['Mark 10 saved mistakes as understood.', 'علّم 10 أخطاء محفوظة على أنها مفهومة.'], 60),
  A('level-up-5', 'ArrowUpCircle', ['Explorer', 'مستكشف'], ['Reach player level 5.', 'بلغ المستوى 5.'], 50),
  A('level-up-10', 'Compass', ['Problem Solver', 'حلّال المسائل'], ['Reach player level 10.', 'بلغ المستوى 10.'], 100),
  A('level-up-20', 'Infinity', ['Math Thinker', 'مفكّر رياضي'], ['Reach player level 20.', 'بلغ المستوى 20.'], 250),
  A('night-owl', 'Moon', ['Night Owl', 'بومة الليل'], ['Practise after 11 pm.', 'تدرّب بعد الساعة 11 مساءً.'], 15, true),
  A('early-bird', 'Sunrise', ['Early Bird', 'طائر الصباح'], ['Practise before 7 am.', 'تدرّب قبل الساعة 7 صباحًا.'], 15, true),
  A('comeback', 'RotateCcw', ['Welcome Back', 'عودة حميدة'], ['Return to practice after a week away.', 'عُد إلى التدريب بعد غياب أسبوع.'], 20, true),
  A('placement', 'Compass', ['Know Your Starting Point', 'أعرف نقطة بدايتي'], ['Finish the placement test.', 'أنهِ اختبار تحديد المستوى.'], 30),
  A('formula-fan', 'Heart', ['Formula Fan', 'محب القوانين'], ['Save 5 formulas as favourites.', 'احفظ 5 قوانين في المفضلة.'], 15),
  A('perfectionist', 'Sparkles', ['Perfectionist', 'الكمال'], ['Answer 50 questions in a row right without hints.', 'أجب عن 50 سؤالًا متتاليًا بشكل صحيح دون تلميحات.'], 300, true),
  A('en-first-lesson', 'Languages', ['First English Lesson', 'أول درس إنجليزي'], ['Complete your first English lesson.', 'أكمل أول درس إنجليزي.'], 20),
  A('en-lessons-10', 'BookOpen', ['English Routine', 'روتين الإنجليزية'], ['Complete 10 English lessons.', 'أكمل 10 دروس إنجليزية.'], 80),
  A('en-lessons-all', 'GraduationCap', ['English Graduate', 'خريج الإنجليزية'], ['Complete every English lesson.', 'أكمل جميع الدروس الإنجليزية.'], 400),
  A('en-words-25', 'Layers', ['Word Collector', 'جامع الكلمات'], ['Start learning 25 words.', 'ابدأ تعلّم 25 كلمة.'], 30),
  A('en-words-100', 'Library', ['Growing Vocabulary', 'مفردات تنمو'], ['Start learning 100 words.', 'ابدأ تعلّم 100 كلمة.'], 100),
  A('en-words-mastered', 'Gem', ['Word Master', 'متقن الكلمات'], ['Master 25 words.', 'أتقن 25 كلمة.'], 150),
  A('en-answers-100', 'Target', ['English Practice', 'تدريب الإنجليزية'], ['Answer 100 English questions.', 'أجب عن 100 سؤال إنجليزي.'], 50),
  A('en-writer', 'NotebookPen', ['Little Writer', 'كاتب صغير'], ['Finish 3 writing tasks.', 'أنهِ 3 مهام كتابة.'], 40),
  A('en-speaker', 'Volume2', ['Out Loud', 'بصوت عالٍ'], ['Rate 10 speaking phrases.', 'قيّم 10 عبارات نطق.'], 40),
  A('en-placement', 'Compass', ['English Starting Point', 'نقطة بدايتي في الإنجليزية'], ['Finish the English placement test.', 'أنهِ اختبار تحديد مستوى الإنجليزية.'], 30),
  A('dual-learner', 'Sparkles', ['Dual Learner', 'متعلّم مزدوج'], ['Complete a lesson in both Mathematics and English.', 'أكمل درسًا في الرياضيات وآخر في الإنجليزية.'], 60),
  A('dual-streak', 'Flame', ['Two Subjects, One Habit', 'مادتان وعادة واحدة'], ['Reach a 7-day streak while learning both subjects.', 'بلغ سلسلة 7 أيام مع تعلّم المادتين.'], 200, true),
];

export const ACHIEVEMENT_BY_ID: Record<string, AchievementDef> = Object.fromEntries(ACHIEVEMENTS.map((a) => [a.id, a]));
