import type { Formula, FormulaCategory, L10n } from '@/types';

const l = (en: string, ar: string): L10n => ({ en, ar });

type V = [symbol: string, en: string, ar: string];

function f(
  id: string,
  category: FormulaCategory,
  name: [string, string],
  latex: string,
  explanation: [string, string],
  vars: V[],
  example: { problem: [string, string]; solution: string },
  when: [string, string],
  topicId?: string,
): Formula {
  return {
    id,
    category,
    name: l(...name),
    latex,
    explanation: l(...explanation),
    variables: vars.map(([symbol, en, ar]) => ({ symbol, meaning: l(en, ar) })),
    example: { problem: l(...example.problem), solution: example.solution },
    whenToUse: l(...when),
    topicId,
  };
}

export const FORMULAS: Formula[] = [
  // ───────── Arithmetic ─────────
  f('order-of-ops', 'arithmetic', ['Order of operations', 'ترتيب العمليات'], '\\text{()} \\to \\text{powers} \\to \\times\\div \\to +-',
    ['Brackets first, then powers, then multiplication and division left to right, then addition and subtraction left to right.', 'الأقواس أولًا ثم الأسس ثم الضرب والقسمة من اليسار إلى اليمين ثم الجمع والطرح من اليسار إلى اليمين.'],
    [],
    { problem: ['Compute $2 + 3 \\times 4$.', 'احسب $2 + 3 \\times 4$.'], solution: '3 × 4 = 12, then 2 + 12 = 14' },
    ['Any expression with more than one operation.', 'أي تعبير فيه أكثر من عملية.'], 'order-of-operations'),
  f('division-algorithm', 'arithmetic', ['Division with remainder', 'القسمة مع الباقي'], 'a = b \\times q + r,\\ 0 \\le r < b',
    ['The dividend equals divisor times quotient plus remainder.', 'المقسوم يساوي المقسوم عليه × الناتج + الباقي.'],
    [['a', 'dividend', 'المقسوم'], ['b', 'divisor', 'المقسوم عليه'], ['q', 'quotient', 'ناتج القسمة'], ['r', 'remainder', 'الباقي']],
    { problem: ['Write $47 \\div 6$ with a remainder.', 'اكتب $47 \\div 6$ مع الباقي.'], solution: '47 = 6 × 7 + 5' },
    ['Checking a division, or sharing items that do not split evenly.', 'للتحقق من القسمة أو عند توزيع أشياء لا تنقسم بالتساوي.'], 'division'),
  f('distributive-law', 'arithmetic', ['Distributive law', 'خاصية التوزيع'], 'a(b + c) = ab + ac',
    ['Multiplying a sum equals multiplying each part and adding.', 'ضرب مجموع يساوي ضرب كل جزء ثم الجمع.'],
    [['a, b, c', 'any numbers', 'أي أعداد']],
    { problem: ['Compute $7 \\times 102$ in your head.', 'احسب $7 \\times 102$ ذهنيًا.'], solution: '7 × 100 + 7 × 2 = 714' },
    ['Mental math and expanding brackets.', 'الحساب الذهني وفك الأقواس.'], 'distributive'),
  f('exponent-product', 'arithmetic', ['Product of powers', 'ضرب القوى'], 'a^m \\times a^n = a^{m+n}',
    ['With the same base, add the exponents.', 'عند تساوي الأساس اجمع الأسس.'],
    [['a', 'base', 'الأساس'], ['m, n', 'exponents', 'الأسس']],
    { problem: ['Simplify $2^3 \\times 2^4$.', 'بسّط $2^3 \\times 2^4$.'], solution: '2^7 = 128' },
    ['Multiplying powers with the same base.', 'عند ضرب قوى لها الأساس نفسه.'], 'exponents'),
  f('exponent-quotient', 'arithmetic', ['Quotient of powers', 'قسمة القوى'], '\\frac{a^m}{a^n} = a^{m-n}',
    ['With the same base, subtract the exponents.', 'عند تساوي الأساس اطرح الأسس.'],
    [['a', 'base (not 0)', 'الأساس (غير صفر)'], ['m, n', 'exponents', 'الأسس']],
    { problem: ['Simplify $\\frac{5^6}{5^2}$.', 'بسّط $\\frac{5^6}{5^2}$.'], solution: '5^4 = 625' },
    ['Dividing powers with the same base.', 'عند قسمة قوى لها الأساس نفسه.'], 'exponents'),
  f('power-of-power', 'arithmetic', ['Power of a power', 'قوة القوة'], '(a^m)^n = a^{mn}',
    ['Raising a power to a power multiplies the exponents.', 'رفع قوة إلى قوة يضرب الأسس.'],
    [['a', 'base', 'الأساس'], ['m, n', 'exponents', 'الأسس']],
    { problem: ['Simplify $(3^2)^3$.', 'بسّط $(3^2)^3$.'], solution: '3^6 = 729' },
    ['A power inside brackets raised again.', 'عندما تُرفع قوة بين قوسين إلى قوة أخرى.'], 'exponents'),
  f('rounding-rule', 'arithmetic', ['Average of two numbers', 'منتصف عددين'], '\\text{mid} = \\frac{a + b}{2}',
    ['The number exactly halfway between $a$ and $b$.', 'العدد الواقع في منتصف المسافة بين $a$ و $b$.'],
    [['a, b', 'two numbers', 'عددان']],
    { problem: ['Halfway between 12 and 20?', 'ما العدد في منتصف 12 و 20؟'], solution: '(12 + 20) / 2 = 16' },
    ['Estimating, midpoints, averages of two values.', 'للتقدير والمنتصف ومتوسط قيمتين.']),

  // ───────── Fractions ─────────
  f('equivalent-fraction', 'fractions', ['Equivalent fractions', 'الكسور المتكافئة'], '\\frac{a}{b} = \\frac{a \\times k}{b \\times k}',
    ['Multiply or divide top and bottom by the same non-zero number.', 'اضرب البسط والمقام أو اقسمهما على العدد نفسه غير الصفر.'],
    [['a', 'numerator', 'البسط'], ['b', 'denominator', 'المقام'], ['k', 'any non-zero number', 'أي عدد غير صفر']],
    { problem: ['Write $\\frac{2}{3}$ with denominator 12.', 'اكتب $\\frac{2}{3}$ بمقام 12.'], solution: '2×4 / 3×4 = 8/12' },
    ['Making common denominators or simplifying.', 'لتوحيد المقامات أو للاختصار.'], 'equivalent-fractions'),
  f('add-fractions', 'fractions', ['Adding fractions', 'جمع الكسور'], '\\frac{a}{b} + \\frac{c}{d} = \\frac{ad + bc}{bd}',
    ['Make a common denominator, then add the tops only.', 'وحّد المقامات ثم اجمع البسوط فقط.'],
    [['a, c', 'numerators', 'البسوط'], ['b, d', 'denominators', 'المقامات']],
    { problem: ['$\\frac{1}{2} + \\frac{1}{3}$', '$\\frac{1}{2} + \\frac{1}{3}$'], solution: '(3 + 2) / 6 = 5/6' },
    ['Adding or subtracting fractions with different denominators.', 'لجمع أو طرح كسور مقاماتها مختلفة.'], 'add-sub-fractions'),
  f('multiply-fractions', 'fractions', ['Multiplying fractions', 'ضرب الكسور'], '\\frac{a}{b} \\times \\frac{c}{d} = \\frac{ac}{bd}',
    ['Multiply the tops, multiply the bottoms.', 'اضرب البسوط واضرب المقامات.'],
    [['a, c', 'numerators', 'البسوط'], ['b, d', 'denominators', 'المقامات']],
    { problem: ['$\\frac{2}{3} \\times \\frac{3}{4}$', '$\\frac{2}{3} \\times \\frac{3}{4}$'], solution: '6/12 = 1/2' },
    ['"Of" a fraction, or scaling by a fraction.', 'لإيجاد جزء من كسر أو للتصغير بكسر.'], 'mul-div-fractions'),
  f('divide-fractions', 'fractions', ['Dividing fractions', 'قسمة الكسور'], '\\frac{a}{b} \\div \\frac{c}{d} = \\frac{a}{b} \\times \\frac{d}{c}',
    ['Keep, change, flip: multiply by the reciprocal.', 'احتفظ بالأول وغيّر العملية واقلب الثاني: اضرب في المقلوب.'],
    [['c/d', 'the divisor (not 0)', 'المقسوم عليه (غير صفر)']],
    { problem: ['$\\frac{3}{4} \\div \\frac{3}{8}$', '$\\frac{3}{4} \\div \\frac{3}{8}$'], solution: '3/4 × 8/3 = 2' },
    ['How many times one fraction fits in another.', 'لمعرفة كم مرة يتسع كسر في آخر.'], 'mul-div-fractions'),
  f('mixed-to-improper', 'fractions', ['Mixed to improper', 'من عدد كسري إلى كسر غير فعلي'], 'w\\tfrac{a}{b} = \\frac{wb + a}{b}',
    ['Multiply the whole by the denominator, add the numerator, keep the denominator.', 'اضرب العدد الصحيح في المقام وأضف البسط وأبقِ المقام.'],
    [['w', 'whole part', 'الجزء الصحيح'], ['a/b', 'fraction part', 'الجزء الكسري']],
    { problem: ['Convert $2\\tfrac{3}{5}$.', 'حوّل $2\\tfrac{3}{5}$.'], solution: '(2×5 + 3)/5 = 13/5' },
    ['Before multiplying or dividing mixed numbers.', 'قبل ضرب الأعداد الكسرية أو قسمتها.'], 'mixed-numbers'),
  f('fraction-to-decimal', 'fractions', ['Fraction to decimal', 'من كسر إلى عدد عشري'], '\\frac{a}{b} = a \\div b',
    ['A fraction bar means divide.', 'خط الكسر يعني قسمة.'],
    [['a', 'numerator', 'البسط'], ['b', 'denominator', 'المقام']],
    { problem: ['Write $\\frac{3}{8}$ as a decimal.', 'اكتب $\\frac{3}{8}$ كعدد عشري.'], solution: '3 ÷ 8 = 0.375' },
    ['Comparing a fraction with a decimal or percent.', 'لمقارنة كسر مع عدد عشري أو نسبة.'], 'fraction-decimal'),

  // ───────── Percentages ─────────
  f('percent-of', 'percentages', ['Percent of a number', 'نسبة مئوية من عدد'], '\\text{part} = \\frac{p}{100} \\times \\text{whole}',
    ['Turn the percent into a fraction of 100 and multiply.', 'حوّل النسبة إلى كسر من 100 ثم اضرب.'],
    [['p', 'percent', 'النسبة المئوية'], ['whole', 'the full amount', 'المقدار الكامل']],
    { problem: ['What is 15% of 80?', 'كم يساوي 15% من 80؟'], solution: '0.15 × 80 = 12' },
    ['Tips, taxes, discounts, shares.', 'البقشيش والضرائب والخصومات والحصص.'], 'percent-of'),
  f('find-percent', 'percentages', ['What percent is it?', 'كم تبلغ النسبة؟'], 'p = \\frac{\\text{part}}{\\text{whole}} \\times 100',
    ['Divide part by whole and multiply by 100.', 'اقسم الجزء على الكل واضرب في 100.'],
    [['part', 'the portion', 'الجزء'], ['whole', 'the total', 'الكل']],
    { problem: ['18 out of 24 is what percent?', '18 من 24 كم نسبتها؟'], solution: '18/24 × 100 = 75%' },
    ['Scores, shares, completion.', 'الدرجات والحصص ونسبة الإنجاز.'], 'percent-basics'),
  f('percent-change', 'percentages', ['Percent change', 'نسبة التغيّر'], '\\frac{\\text{new} - \\text{old}}{\\text{old}} \\times 100',
    ['The change divided by the original value, as a percent.', 'التغيّر مقسومًا على القيمة الأصلية، كنسبة مئوية.'],
    [['old', 'starting value', 'القيمة الأولى'], ['new', 'final value', 'القيمة النهائية']],
    { problem: ['A price goes from 50 to 65.', 'ارتفع سعر من 50 إلى 65.'], solution: '(65 − 50)/50 × 100 = 30% increase' },
    ['Growth, price changes, comparisons over time.', 'للنمو وتغيّر الأسعار والمقارنة عبر الزمن.'], 'discounts'),
  f('sale-price', 'percentages', ['Price after discount', 'السعر بعد الخصم'], '\\text{price} \\times \\left(1 - \\frac{d}{100}\\right)',
    ['Multiply by what you still pay: 100% minus the discount.', 'اضرب في ما تدفعه فعلًا: 100% ناقص الخصم.'],
    [['price', 'original price', 'السعر الأصلي'], ['d', 'discount percent', 'نسبة الخصم']],
    { problem: ['A 120 jacket is 25% off.', 'سترة بـ 120 عليها خصم 25%.'], solution: '120 × 0.75 = 90' },
    ['Sales and coupons.', 'التخفيضات والقسائم.'], 'discounts'),
  f('simple-interest', 'percentages', ['Simple interest', 'الفائدة البسيطة'], 'I = P \\times r \\times t',
    ['Interest grows by the same amount each year.', 'تزيد الفائدة بالمقدار نفسه كل سنة.'],
    [['P', 'principal', 'المبلغ الأصلي'], ['r', 'yearly rate (decimal)', 'المعدل السنوي (عشري)'], ['t', 'years', 'السنوات']],
    { problem: ['1000 at 5% for 3 years.', '1000 بفائدة 5% لمدة 3 سنوات.'], solution: '1000 × 0.05 × 3 = 150' },
    ['Loans and savings with no compounding.', 'القروض والمدخرات دون فائدة مركبة.']),
  f('compound-interest', 'percentages', ['Compound interest', 'الفائدة المركبة'], 'A = P\\left(1 + r\\right)^t',
    ['Each year the interest is earned on the new total.', 'تُحسب الفائدة كل سنة على المجموع الجديد.'],
    [['A', 'final amount', 'المبلغ النهائي'], ['P', 'starting amount', 'المبلغ الأولي'], ['r', 'rate per period', 'المعدل للفترة'], ['t', 'number of periods', 'عدد الفترات']],
    { problem: ['1000 at 10% for 2 years.', '1000 بفائدة 10% لسنتين.'], solution: '1000 × 1.1² = 1210' },
    ['Savings that grow on themselves, and population growth.', 'مدخرات تنمو على نفسها ونمو السكان.']),

  // ───────── Algebra ─────────
  f('ratio-proportion', 'algebra', ['Proportion', 'التناسب'], '\\frac{a}{b} = \\frac{c}{d} \\iff ad = bc',
    ['Cross-multiply to solve for a missing term.', 'اضرب تبادليًا لإيجاد الحد المجهول.'],
    [['a, b, c, d', 'the four terms', 'الحدود الأربعة']],
    { problem: ['$\\frac{3}{4} = \\frac{x}{20}$', '$\\frac{3}{4} = \\frac{x}{20}$'], solution: '4x = 60, x = 15' },
    ['Recipes, scales and maps.', 'الوصفات ومقاييس الرسم والخرائط.'], 'proportions'),
  f('speed', 'algebra', ['Speed, distance, time', 'السرعة والمسافة والزمن'], 'd = v \\times t',
    ['Distance equals speed times time. Rearrange for the others.', 'المسافة تساوي السرعة × الزمن. أعد الترتيب لإيجاد الباقي.'],
    [['d', 'distance', 'المسافة'], ['v', 'speed', 'السرعة'], ['t', 'time', 'الزمن']],
    { problem: ['60 km/h for 2.5 hours.', '60 كم/س لمدة 2.5 ساعة.'], solution: '60 × 2.5 = 150 km' },
    ['Travel and rate problems.', 'مسائل السفر والمعدلات.'], 'proportions'),
  f('linear-equation', 'algebra', ['Line equation', 'معادلة المستقيم'], 'y = mx + b',
    ['$m$ is the slope; $b$ is where the line crosses the $y$-axis.', '$m$ هو الميل و $b$ هو نقطة تقاطع المستقيم مع المحور $y$.'],
    [['m', 'slope', 'الميل'], ['b', 'y-intercept', 'المقطع الصادي']],
    { problem: ['Line through $(0, 3)$ with slope 2.', 'مستقيم يمر بـ $(0, 3)$ وميله 2.'], solution: 'y = 2x + 3' },
    ['Constant rates of change.', 'معدلات التغيّر الثابتة.'], 'linear-functions'),
  f('slope', 'algebra', ['Slope', 'الميل'], 'm = \\frac{y_2 - y_1}{x_2 - x_1}',
    ['Rise over run between two points.', 'الارتفاع على الامتداد بين نقطتين.'],
    [['(x₁, y₁), (x₂, y₂)', 'two points', 'نقطتان']],
    { problem: ['Points $(1, 2)$ and $(3, 8)$.', 'النقطتان $(1, 2)$ و $(3, 8)$.'], solution: '(8 − 2)/(3 − 1) = 3' },
    ['How steep a line is.', 'لمعرفة مدى انحدار مستقيم.'], 'linear-functions'),
  f('difference-squares', 'algebra', ['Difference of squares', 'فرق مربعين'], 'a^2 - b^2 = (a - b)(a + b)',
    ['Two perfect squares subtracted factor into a sum and difference.', 'مربعان كاملان بينهما طرح يتحللان إلى مجموع وفرق.'],
    [['a, b', 'any terms', 'أي حدود']],
    { problem: ['Factor $x^2 - 25$.', 'حلّل $x^2 - 25$.'], solution: '(x − 5)(x + 5)' },
    ['Factoring and fast mental products ($49 \\times 51$).', 'للتحليل ولحسابات ذهنية سريعة ($49 \\times 51$).'], 'factoring'),
  f('square-binomial', 'algebra', ['Square of a binomial', 'مربع ذات الحدين'], '(a \\pm b)^2 = a^2 \\pm 2ab + b^2',
    ['Do not forget the middle term $2ab$.', 'لا تنسَ الحد الأوسط $2ab$.'],
    [['a, b', 'any terms', 'أي حدود']],
    { problem: ['Expand $(x + 3)^2$.', 'وسّع $(x + 3)^2$.'], solution: 'x² + 6x + 9' },
    ['Expanding or recognising perfect squares.', 'للتوسيع أو لمعرفة المربعات الكاملة.'], 'factoring'),
  f('quadratic-formula', 'algebra', ['Quadratic formula', 'القانون العام'], 'x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}',
    ['Solves any $ax^2 + bx + c = 0$.', 'يحلّ أي معادلة $ax^2 + bx + c = 0$.'],
    [['a, b, c', 'coefficients (a ≠ 0)', 'المعاملات (a ≠ 0)']],
    { problem: ['Solve $x^2 - 5x + 6 = 0$.', 'حلّ $x^2 - 5x + 6 = 0$.'], solution: 'x = (5 ± 1)/2 → 3 or 2' },
    ['When factoring is hard.', 'عندما يصعب التحليل.'], 'quadratics'),
  f('discriminant', 'algebra', ['Discriminant', 'المميّز'], '\\Delta = b^2 - 4ac',
    ['Positive: two roots. Zero: one root. Negative: none.', 'موجب: جذران. صفر: جذر واحد. سالب: لا جذور.'],
    [['Δ', 'discriminant', 'المميّز']],
    { problem: ['$x^2 + 2x + 5 = 0$', '$x^2 + 2x + 5 = 0$'], solution: 'Δ = 4 − 20 = −16 → no real roots' },
    ['Counting solutions before solving.', 'لمعرفة عدد الحلول قبل الحل.'], 'quadratics'),
  f('vertex-x', 'algebra', ['Parabola vertex', 'رأس القطع المكافئ'], 'x_v = -\\frac{b}{2a}',
    ['The axis of symmetry passes through the vertex.', 'محور التناظر يمر برأس القطع.'],
    [['a, b', 'coefficients of $ax^2 + bx + c$', 'معاملا $ax^2 + bx + c$']],
    { problem: ['Vertex of $y = x^2 - 6x + 5$.', 'رأس $y = x^2 - 6x + 5$.'], solution: 'x = 6/2 = 3' },
    ['Maximum or minimum of a quadratic.', 'القيمة العظمى أو الصغرى لتربيعية.'], 'quadratics'),
  f('arith-nth', 'algebra', ['Arithmetic sequence term', 'حد المتتالية الحسابية'], 'a_n = a_1 + (n - 1)d',
    ['Start at $a_1$ and add $d$ a total of $n-1$ times.', 'ابدأ من $a_1$ وأضف $d$ عدد $n-1$ مرة.'],
    [['a₁', 'first term', 'الحد الأول'], ['d', 'common difference', 'الأساس (الفرق)'], ['n', 'position', 'ترتيب الحد']],
    { problem: ['20th term of 4, 7, 10…', 'الحد العشرون في 4 و7 و10…'], solution: '4 + 19×3 = 61' },
    ['Linear patterns.', 'الأنماط الخطية.'], 'sequences'),
  f('arith-sum', 'algebra', ['Arithmetic series sum', 'مجموع متتالية حسابية'], 'S_n = \\frac{n}{2}(a_1 + a_n)',
    ['Average of first and last, times the number of terms.', 'متوسط الأول والأخير مضروبًا في عدد الحدود.'],
    [['n', 'number of terms', 'عدد الحدود'], ['a₁, aₙ', 'first and last term', 'الحد الأول والأخير']],
    { problem: ['Sum of 1 to 100.', 'مجموع الأعداد من 1 إلى 100.'], solution: '100/2 × 101 = 5050' },
    ['Adding evenly-spaced numbers.', 'جمع أعداد متساوية البعد.'], 'sequences'),
  f('geom-nth', 'algebra', ['Geometric sequence term', 'حد المتتالية الهندسية'], 'a_n = a_1 \\cdot r^{n-1}',
    ['Start at $a_1$ and multiply by $r$ a total of $n-1$ times.', 'ابدأ من $a_1$ واضرب في $r$ عدد $n-1$ مرة.'],
    [['a₁', 'first term', 'الحد الأول'], ['r', 'common ratio', 'النسبة المشتركة']],
    { problem: ['6th term of 2, 6, 18…', 'الحد السادس في 2 و6 و18…'], solution: '2 × 3⁵ = 486' },
    ['Doubling, halving, compound growth.', 'المضاعفة والتنصيف والنمو المركب.'], 'sequences'),
  f('log-def', 'algebra', ['Logarithm', 'اللوغاريتم'], '\\log_b x = y \\iff b^y = x',
    ['A logarithm is the exponent you need.', 'اللوغاريتم هو الأس المطلوب.'],
    [['b', 'base', 'الأساس'], ['x', 'positive number', 'عدد موجب'], ['y', 'exponent', 'الأس']],
    { problem: ['$\\log_2 32$', '$\\log_2 32$'], solution: '2⁵ = 32, so 5' },
    ['Solving for an unknown exponent.', 'لإيجاد أس مجهول.'], 'logs-scientific'),
  f('log-product', 'algebra', ['Log of a product', 'لوغاريتم الضرب'], '\\log(xy) = \\log x + \\log y',
    ['Multiplication inside a log becomes addition outside.', 'الضرب داخل اللوغاريتم يصبح جمعًا خارجه.'],
    [['x, y', 'positive numbers', 'أعداد موجبة']],
    { problem: ['$\\log 2 + \\log 5$', '$\\log 2 + \\log 5$'], solution: 'log 10 = 1' },
    ['Simplifying logarithms.', 'لتبسيط اللوغاريتمات.'], 'logs-scientific'),
  f('scientific-notation', 'algebra', ['Scientific notation', 'الصيغة العلمية'], 'N = a \\times 10^n,\\ 1 \\le a < 10',
    ['Move the decimal point until one non-zero digit is left of it; count the moves.', 'حرّك الفاصلة حتى يبقى رقم واحد غير صفري قبلها واحسب عدد الخطوات.'],
    [['a', 'coefficient', 'المعامل'], ['n', 'integer exponent', 'الأس الصحيح']],
    { problem: ['Write 0.00045.', 'اكتب 0.00045.'], solution: '4.5 × 10⁻⁴' },
    ['Very large or very small numbers.', 'الأعداد الكبيرة جدًا أو الصغيرة جدًا.'], 'logs-scientific'),

  // ───────── Geometry ─────────
  f('rect-area', 'geometry', ['Rectangle area', 'مساحة المستطيل'], 'A = l \\times w',
    ['Length times width.', 'الطول × العرض.'],
    [['l', 'length', 'الطول'], ['w', 'width', 'العرض']],
    { problem: ['8 m by 5 m.', '8 م × 5 م.'], solution: '40 m²' },
    ['Floors, walls, land.', 'الأرضيات والجدران والأراضي.'], 'area'),
  f('rect-perimeter', 'geometry', ['Rectangle perimeter', 'محيط المستطيل'], 'P = 2(l + w)',
    ['Twice the sum of length and width.', 'ضعف مجموع الطول والعرض.'],
    [['l', 'length', 'الطول'], ['w', 'width', 'العرض']],
    { problem: ['8 m by 5 m.', '8 م × 5 م.'], solution: '26 m' },
    ['Fences and borders.', 'الأسوار والحدود.'], 'perimeter'),
  f('triangle-area', 'geometry', ['Triangle area', 'مساحة المثلث'], 'A = \\tfrac{1}{2} b h',
    ['Half of base times perpendicular height.', 'نصف القاعدة × الارتفاع العمودي.'],
    [['b', 'base', 'القاعدة'], ['h', 'height', 'الارتفاع']],
    { problem: ['b = 10, h = 6.', 'القاعدة 10 والارتفاع 6.'], solution: '30' },
    ['Any triangle.', 'أي مثلث.'], 'area'),
  f('trapezoid-area', 'geometry', ['Trapezoid area', 'مساحة شبه المنحرف'], 'A = \\frac{a + b}{2} \\cdot h',
    ['Average of the parallel sides times the height.', 'متوسط الضلعين المتوازيين × الارتفاع.'],
    [['a, b', 'parallel sides', 'الضلعان المتوازيان'], ['h', 'height', 'الارتفاع']],
    { problem: ['a = 6, b = 10, h = 4.', 'a = 6 و b = 10 و h = 4.'], solution: '32' },
    ['Shapes with exactly one pair of parallel sides.', 'أشكال بزوج واحد من الأضلاع المتوازية.'], 'area'),
  f('circle-area', 'geometry', ['Circle area', 'مساحة الدائرة'], 'A = \\pi r^2',
    ['Pi times the radius squared.', 'باي × مربع نصف القطر.'],
    [['r', 'radius', 'نصف القطر']],
    { problem: ['r = 3.', 'نصف القطر 3.'], solution: '9π ≈ 28.27' },
    ['Round surfaces.', 'الأسطح الدائرية.'], 'circles'),
  f('circumference', 'geometry', ['Circumference', 'محيط الدائرة'], 'C = 2\\pi r = \\pi d',
    ['The distance around a circle.', 'المسافة حول الدائرة.'],
    [['r', 'radius', 'نصف القطر'], ['d', 'diameter', 'القطر']],
    { problem: ['d = 10.', 'القطر 10.'], solution: '10π ≈ 31.4' },
    ['Wheels, belts, edging.', 'العجلات والأحزمة والحواف.'], 'circles'),
  f('pythagoras', 'geometry', ['Pythagorean theorem', 'نظرية فيثاغورس'], 'a^2 + b^2 = c^2',
    ['In a right triangle the squares on the legs add to the square on the hypotenuse.', 'في المثلث القائم مجموع مربعي الضلعين يساوي مربع الوتر.'],
    [['a, b', 'legs', 'الضلعان القائمان'], ['c', 'hypotenuse', 'الوتر']],
    { problem: ['Legs 6 and 8.', 'الضلعان 6 و 8.'], solution: 'c = √100 = 10' },
    ['Right triangles, diagonals, distances.', 'المثلثات القائمة والأقطار والمسافات.'], 'triangles'),
  f('angle-sum-triangle', 'geometry', ['Triangle angle sum', 'مجموع زوايا المثلث'], '\\alpha + \\beta + \\gamma = 180^\\circ',
    ['The three angles of a triangle always total 180°.', 'زوايا المثلث الثلاث مجموعها دائمًا 180°.'],
    [['α, β, γ', 'the three angles', 'الزوايا الثلاث']],
    { problem: ['Angles 50° and 70°.', 'زاويتان 50° و 70°.'], solution: '180 − 120 = 60°' },
    ['Finding a missing angle.', 'لإيجاد زاوية مجهولة.'], 'angles'),
  f('cuboid-volume', 'geometry', ['Cuboid volume', 'حجم متوازي المستطيلات'], 'V = l \\times w \\times h',
    ['Base area times height.', 'مساحة القاعدة × الارتفاع.'],
    [['l, w, h', 'length, width, height', 'الطول والعرض والارتفاع']],
    { problem: ['4 × 3 × 5.', '4 × 3 × 5.'], solution: '60' },
    ['Boxes, rooms, tanks.', 'الصناديق والغرف والخزانات.'], 'volume'),
  f('cylinder-volume', 'geometry', ['Cylinder volume', 'حجم الأسطوانة'], 'V = \\pi r^2 h',
    ['Circle area times height.', 'مساحة الدائرة × الارتفاع.'],
    [['r', 'radius', 'نصف القطر'], ['h', 'height', 'الارتفاع']],
    { problem: ['r = 2, h = 5.', 'r = 2 و h = 5.'], solution: '20π ≈ 62.8' },
    ['Cans, pipes, columns.', 'العلب والأنابيب والأعمدة.'], 'volume'),
  f('distance-2d', 'geometry', ['Distance between points', 'المسافة بين نقطتين'], 'd = \\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}',
    ['Pythagoras on the horizontal and vertical differences.', 'فيثاغورس على الفرقين الأفقي والرأسي.'],
    [['(x₁, y₁), (x₂, y₂)', 'two points', 'نقطتان']],
    { problem: ['$(0,0)$ to $(6,8)$.', 'من $(0,0)$ إلى $(6,8)$.'], solution: '√(36 + 64) = 10' },
    ['Distances on a map or grid.', 'المسافات على خريطة أو شبكة.'], 'coordinate'),
  f('midpoint', 'geometry', ['Midpoint', 'نقطة المنتصف'], 'M = \\left(\\frac{x_1 + x_2}{2}, \\frac{y_1 + y_2}{2}\\right)',
    ['Average the coordinates.', 'خذ متوسط الإحداثيات.'],
    [['(x₁, y₁), (x₂, y₂)', 'endpoints', 'الطرفان']],
    { problem: ['$(2,4)$ and $(8,10)$.', '$(2,4)$ و $(8,10)$.'], solution: '(5, 7)' },
    ['Centres of segments.', 'مراكز القطع المستقيمة.'], 'coordinate'),

  // ───────── Trigonometry ─────────
  f('sin', 'trigonometry', ['Sine', 'الجيب'], '\\sin\\theta = \\frac{\\text{opposite}}{\\text{hypotenuse}}',
    ['Opposite side over hypotenuse.', 'المقابل على الوتر.'],
    [['θ', 'the angle', 'الزاوية']],
    { problem: ['Hypotenuse 10, angle 30°. Opposite side?', 'الوتر 10 والزاوية 30°. ما المقابل؟'], solution: '10 × 0.5 = 5' },
    ['You know the hypotenuse or want it, and need the opposite.', 'عندما يتعلق الأمر بالوتر والمقابل.'], 'trigonometry'),
  f('cos', 'trigonometry', ['Cosine', 'جيب التمام'], '\\cos\\theta = \\frac{\\text{adjacent}}{\\text{hypotenuse}}',
    ['Adjacent side over hypotenuse.', 'المجاور على الوتر.'],
    [['θ', 'the angle', 'الزاوية']],
    { problem: ['Hypotenuse 10, angle 60°. Adjacent?', 'الوتر 10 والزاوية 60°. ما المجاور؟'], solution: '10 × 0.5 = 5' },
    ['Hypotenuse and adjacent side.', 'عندما يتعلق الأمر بالوتر والمجاور.'], 'trigonometry'),
  f('tan', 'trigonometry', ['Tangent', 'الظل'], '\\tan\\theta = \\frac{\\text{opposite}}{\\text{adjacent}}',
    ['Opposite over adjacent. Also equals the slope.', 'المقابل على المجاور. ويساوي أيضًا الميل.'],
    [['θ', 'the angle', 'الزاوية']],
    { problem: ['Angle 45°, adjacent 7. Opposite?', 'الزاوية 45° والمجاور 7. ما المقابل؟'], solution: '7 × 1 = 7' },
    ['The two legs, no hypotenuse.', 'عندما يتعلق الأمر بالضلعين القائمين فقط.'], 'trigonometry'),
  f('pyth-identity', 'trigonometry', ['Pythagorean identity', 'المتطابقة الأساسية'], '\\sin^2\\theta + \\cos^2\\theta = 1',
    ['True for every angle.', 'صحيحة لكل زاوية.'],
    [['θ', 'any angle', 'أي زاوية']],
    { problem: ['If $\\sin\\theta = 0.6$, find $\\cos\\theta$ (acute).', 'إذا كان $\\sin\\theta = 0.6$ فأوجد $\\cos\\theta$ (حادة).'], solution: '√(1 − 0.36) = 0.8' },
    ['Finding one ratio from another.', 'لإيجاد نسبة من أخرى.'], 'trigonometry'),

  // ───────── Statistics ─────────
  f('mean', 'statistics', ['Mean', 'المتوسط الحسابي'], '\\bar{x} = \\frac{\\sum x}{n}',
    ['Sum of the values divided by how many there are.', 'مجموع القيم مقسومًا على عددها.'],
    [['Σx', 'sum of values', 'مجموع القيم'], ['n', 'number of values', 'عدد القيم']],
    { problem: ['2, 4, 9.', '2 و4 و9.'], solution: '15 / 3 = 5' },
    ['A typical value for fairly even data.', 'قيمة نموذجية للبيانات المتقاربة.'], 'statistics'),
  f('median', 'statistics', ['Median', 'الوسيط'], '\\text{middle value of sorted data}',
    ['Sort the data. With an even count, average the two middle values.', 'رتّب البيانات. وإذا كان العدد زوجيًا فخذ متوسط القيمتين الوسطيتين.'],
    [],
    { problem: ['1, 3, 8, 10.', '1 و3 و8 و10.'], solution: '(3 + 8)/2 = 5.5' },
    ['Data with outliers.', 'البيانات التي فيها قيم شاذة.'], 'statistics'),
  f('range', 'statistics', ['Range', 'المدى'], '\\text{range} = \\max - \\min',
    ['How far apart the extremes are.', 'مدى بعد الطرفين عن بعضهما.'],
    [],
    { problem: ['4, 9, 15.', '4 و9 و15.'], solution: '15 − 4 = 11' },
    ['A quick measure of spread.', 'مقياس سريع للتشتت.'], 'statistics'),
  f('std-dev', 'statistics', ['Standard deviation', 'الانحراف المعياري'], '\\sigma = \\sqrt{\\frac{\\sum (x - \\bar{x})^2}{n}}',
    ['The typical distance of values from the mean.', 'البعد النموذجي للقيم عن المتوسط.'],
    [['x̄', 'mean', 'المتوسط'], ['n', 'number of values', 'عدد القيم']],
    { problem: ['2, 4, 6.', '2 و4 و6.'], solution: 'mean 4; √((4+0+4)/3) ≈ 1.63' },
    ['Comparing how spread out two data sets are.', 'لمقارنة تشتت مجموعتين من البيانات.'], 'statistics'),

  // ───────── Probability ─────────
  f('prob-basic', 'probability', ['Basic probability', 'الاحتمال الأساسي'], 'P(A) = \\frac{\\text{favourable}}{\\text{total}}',
    ['Favourable outcomes divided by all equally likely outcomes.', 'النتائج المرغوبة مقسومة على كل النتائج المتساوية الفرصة.'],
    [['P(A)', 'probability of A', 'احتمال A']],
    { problem: ['Rolling a 5 or 6 on a die.', 'ظهور 5 أو 6 على حجر نرد.'], solution: '2/6 = 1/3' },
    ['Fair dice, coins, cards, bags.', 'النرد والعملات والأوراق والأكياس العادلة.'], 'probability'),
  f('prob-complement', 'probability', ['Complement', 'الحدث المتمم'], 'P(\\text{not } A) = 1 - P(A)',
    ['Chance it does not happen.', 'فرصة ألا يحدث.'],
    [['P(A)', 'probability of A', 'احتمال A']],
    { problem: ['P(rain) = 0.3.', 'احتمال المطر 0.3.'], solution: '1 − 0.3 = 0.7' },
    ['"At least one" problems.', 'مسائل "على الأقل واحد".'], 'probability'),
  f('prob-and', 'probability', ['Independent events (and)', 'حوادث مستقلة (و)'], 'P(A \\text{ and } B) = P(A) \\times P(B)',
    ['Multiply when one event does not affect the other.', 'اضرب عندما لا يؤثر حدث في الآخر.'],
    [['P(A), P(B)', 'individual probabilities', 'الاحتمالان المنفردان']],
    { problem: ['Two heads in a row.', 'صورتان متتاليتان.'], solution: '½ × ½ = ¼' },
    ['Repeated trials.', 'التجارب المتكررة.'], 'probability'),
  f('prob-or', 'probability', ['Exclusive events (or)', 'حوادث متنافية (أو)'], 'P(A \\text{ or } B) = P(A) + P(B)',
    ['Add when both cannot happen together.', 'اجمع عندما لا يمكن حدوثهما معًا.'],
    [['P(A), P(B)', 'individual probabilities', 'الاحتمالان المنفردان']],
    { problem: ['A die shows 1 or 2.', 'ظهور 1 أو 2 على النرد.'], solution: '1/6 + 1/6 = 1/3' },
    ['Either of several separate outcomes.', 'أي من عدة نتائج منفصلة.'], 'probability'),
  f('expected-value', 'probability', ['Expected value', 'القيمة المتوقعة'], 'E = \\sum x \\cdot P(x)',
    ['The long-run average outcome.', 'متوسط النتيجة على المدى الطويل.'],
    [['x', 'outcome value', 'قيمة النتيجة'], ['P(x)', 'its probability', 'احتمالها']],
    { problem: ['Win 10 with chance 0.2, else 0.', 'تربح 10 باحتمال 0.2 وإلا 0.'], solution: '10 × 0.2 = 2' },
    ['Judging whether a game is worth playing.', 'للحكم على جدوى لعبة.'], 'probability'),
  f('combinations', 'probability', ['Combinations', 'التوافيق'], '\\binom{n}{k} = \\frac{n!}{k!\\,(n-k)!}',
    ['Ways to choose $k$ from $n$ when order does not matter.', 'عدد طرق اختيار $k$ من $n$ حين لا يهم الترتيب.'],
    [['n', 'items available', 'العناصر المتاحة'], ['k', 'items chosen', 'العناصر المختارة']],
    { problem: ['Choose 2 from 5.', 'اختيار 2 من 5.'], solution: '5!/(2!·3!) = 10' },
    ['Teams, hands of cards, committees.', 'الفرق وأوراق اللعب واللجان.']),
];

export const FORMULA_BY_ID: Record<string, Formula> = Object.fromEntries(FORMULAS.map((x) => [x.id, x]));

export const FORMULA_CATEGORIES: FormulaCategory[] = [
  'arithmetic',
  'fractions',
  'percentages',
  'algebra',
  'geometry',
  'trigonometry',
  'statistics',
  'probability',
];
